///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Add_Duplicate_IPAddress_To_DHCP_Reservation_List recording.
    /// </summary>
    [TestModule("ca48f30d-aaa5-43c2-982c-1d4e8f82577c", ModuleType.Recording, 1)]
    public partial class Add_Duplicate_IPAddress_To_DHCP_Reservation_List : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Add_Duplicate_IPAddress_To_DHCP_Reservation_List instance = new Add_Duplicate_IPAddress_To_DHCP_Reservation_List();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Add_Duplicate_IPAddress_To_DHCP_Reservation_List()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Add_Duplicate_IPAddress_To_DHCP_Reservation_List Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //repo.WebDocument19216801.IPAdd2.Click("94;32");
            //Delay.Milliseconds(200);
            
            //Delay.Duration(1000, false);
            
            repo.WebDocument19216801.IPAdd2.DoubleClick("60;22");
            Delay.Milliseconds(200);
            
            Validate.Exists(repo.WebDocument19216801.ErrTipIPv4SrcSingleInfo, "Duplicate IP Address");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='errTip_IPv4SrcSingle') on item 'WebDocument19216801.ErrTipIPv4SrcSingle'.", repo.WebDocument19216801.ErrTipIPv4SrcSingleInfo, new RecordItemIndex(4));
            //Validate.Attribute(repo.WebDocument19216801.ErrTipIPv4SrcSingleInfo, "Id", "errTip_IPv4SrcSingle");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.MacAddress51' at 24;16.", repo.WebDocument19216801.MacAddress51Info, new RecordItemIndex(5));
            //repo.WebDocument19216801.MacAddress51.MoveTo("24;16");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.MacAddress51' at 24;16.", repo.WebDocument19216801.MacAddress51Info, new RecordItemIndex(6));
            //repo.WebDocument19216801.MacAddress51.MoveTo("24;16");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}A{LShiftKey up}' with focus on 'WebDocument19216801.MacAddress51'.", repo.WebDocument19216801.MacAddress51Info, new RecordItemIndex(7));
            //repo.WebDocument19216801.MacAddress51.PressKeys("{LShiftKey down}A{LShiftKey up}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'WebDocument19216801.MacAddress41' at 16;10.", repo.WebDocument19216801.MacAddress41Info, new RecordItemIndex(8));
            //repo.WebDocument19216801.MacAddress41.DoubleClick("16;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '23' with focus on 'WebDocument19216801.MacAddress41'.", repo.WebDocument19216801.MacAddress41Info, new RecordItemIndex(9));
            //repo.WebDocument19216801.MacAddress41.PressKeys("23");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.IPAdd2' at 62;27.", repo.WebDocument19216801.IPAdd2Info, new RecordItemIndex(10));
            //repo.WebDocument19216801.IPAdd2.Click("62;27");
            //Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "Duplicate Ip Address", null, false, new RecordItemIndex(11));
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
