///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Allow_Add_Device_To_Mac_List_5GHz_Prmy recording.
    /// </summary>
    [TestModule("d08a0d17-09f2-4b47-9e86-8c6eb3380300", ModuleType.Recording, 1)]
    public partial class Allow_Add_Device_To_Mac_List_5GHz_Prmy : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Allow_Add_Device_To_Mac_List_5GHz_Prmy instance = new Allow_Add_Device_To_Mac_List_5GHz_Prmy();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Allow_Add_Device_To_Mac_List_5GHz_Prmy()
        {
            Mac0 = "";
            Mac1 = "";
            Mac2 = "";
            Mac3 = "";
            Mac4 = "";
            Mac5 = "";
            Filter_Option = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Allow_Add_Device_To_Mac_List_5GHz_Prmy Instance
        {
            get { return instance; }
        }

#region Variables

        string _Mac0;

        /// <summary>
        /// Gets or sets the value of variable Mac0.
        /// </summary>
        [TestVariable("9c87d307-c991-49a7-a2e7-98bc9e80c83c")]
        public string Mac0
        {
            get { return _Mac0; }
            set { _Mac0 = value; }
        }

        string _Mac1;

        /// <summary>
        /// Gets or sets the value of variable Mac1.
        /// </summary>
        [TestVariable("a6057b88-a458-425b-bfc6-154ff3fe0397")]
        public string Mac1
        {
            get { return _Mac1; }
            set { _Mac1 = value; }
        }

        string _Mac2;

        /// <summary>
        /// Gets or sets the value of variable Mac2.
        /// </summary>
        [TestVariable("27b49550-c93f-4fb4-805b-0c862942b56b")]
        public string Mac2
        {
            get { return _Mac2; }
            set { _Mac2 = value; }
        }

        string _Mac3;

        /// <summary>
        /// Gets or sets the value of variable Mac3.
        /// </summary>
        [TestVariable("5a3d24ed-ae4f-4c2e-98b0-648a768c2e1d")]
        public string Mac3
        {
            get { return _Mac3; }
            set { _Mac3 = value; }
        }

        string _Mac4;

        /// <summary>
        /// Gets or sets the value of variable Mac4.
        /// </summary>
        [TestVariable("6aa1637f-3624-4aad-9b52-ed7dfb228f3f")]
        public string Mac4
        {
            get { return _Mac4; }
            set { _Mac4 = value; }
        }

        string _Mac5;

        /// <summary>
        /// Gets or sets the value of variable Mac5.
        /// </summary>
        [TestVariable("c3451fac-9a03-48a3-934f-ada8ec3bfd56")]
        public string Mac5
        {
            get { return _Mac5; }
            set { _Mac5 = value; }
        }

        string _Filter_Option;

        /// <summary>
        /// Gets or sets the value of variable Filter_Option.
        /// </summary>
        [TestVariable("a3eb629a-9f1b-4fdc-90cc-7cfef0d2ca4c")]
        public string Filter_Option
        {
            get { return _Filter_Option; }
            set { _Filter_Option = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Choose_Attached_Devices_To_Add_5GHz_Primary(Mac0, Mac1, Mac2, Mac3, Mac4, Mac5, Filter_Option);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            //Select_Attached_5GHz_Primary_Devices_To_Add(Mac0, Mac1, Mac2, Mac3, Mac4, Mac5, Filter_Option);
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
