///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Apply_Rule_Changes recording.
    /// </summary>
    [TestModule("8802cbb7-6b22-4793-9fdb-dd9b1f0092a2", ModuleType.Recording, 1)]
    public partial class Apply_Rule_Changes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Apply_Rule_Changes instance = new Apply_Rule_Changes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Apply_Rule_Changes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Apply_Rule_Changes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.WebDocument19216801' at 1354;400.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(0));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1354;400");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1357;493.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(1));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1357;493");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Add rule') on item 'WebDocument19216801.AddApply'.", repo.WebDocument19216801.AddApplyInfo, new RecordItemIndex(2));
            //Validate.Attribute(repo.WebDocument19216801.AddApplyInfo, "Value", "Add rule");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.AddApply' at 55;26.", repo.WebDocument19216801.AddApplyInfo, new RecordItemIndex(3));
            //repo.WebDocument19216801.AddApply.Click("55;26");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmRbtnAlwaysLimitation' at 11;14.", repo.WebDocument19216801.FmRbtnAlwaysLimitationInfo, new RecordItemIndex(4));
            //repo.WebDocument19216801.FmRbtnAlwaysLimitation.Click("11;14");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Apply changes') on item 'WebDocument19216801.Button6'.", repo.WebDocument19216801.Button6Info, new RecordItemIndex(5));
            //Validate.Attribute(repo.WebDocument19216801.Button6Info, "Value", "Apply changes");
            //Delay.Milliseconds(100);
            
            try {
                //Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'WebDocument19216801.Button6' at 86;26.", repo.WebDocument19216801.Button6Info, new RecordItemIndex(6));
                //repo.WebDocument19216801.Button6.Click("86;26");
                //Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(6)); }
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='commonApply') on item 'WebDocument19216801.Button15'.", repo.WebDocument19216801.Button15Info, new RecordItemIndex(7));
            //Validate.Attribute(repo.WebDocument19216801.Button15Info, "Id", "commonApply");
            //Delay.Milliseconds(100);
            
            Validate.Attribute(repo.WebDocument19216801.Button15Info, "TagValue", "Apply changes");
            Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.Button15Info, "Tabindex", "21");
            //Delay.Milliseconds(100);
            
            Validate.Attribute(repo.WebDocument19216801.Button15Info, "Value", "Apply changes");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=213,Height=56}) on item 'WebDocument19216801.Button15'.", repo.WebDocument19216801.Button15Info, new RecordItemIndex(11));
            //Validate.ContainsImage(repo.WebDocument19216801.Button15Info, Button15_Screenshot1, Button15_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            repo.WebDocument19216801.Button15.Click("93;33");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Button25' at 117;22.", repo.WebDocument19216801.Button25Info, new RecordItemIndex(13));
            //repo.WebDocument19216801.Button25.Click("117;22");
            //Delay.Milliseconds(200);
            
            Validate.Attribute(repo.WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdatedInfo, "Class", "confirm-wizard-text");
            Delay.Milliseconds(100);
            
            Validate.Attribute(repo.WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdatedInfo, "InnerText", "Your settings have been updated.");
            Delay.Milliseconds(100);
            
            Validate.Attribute(repo.WebDocument19216801.SettingsUpdatesSuccessSettingsUpdateInfo, "Class", "settings-updates-success");
            Delay.Milliseconds(100);
            
            Validate.Attribute(repo.WebDocumentIE.ConfirmWizard1.Http19216801IAllgoodIconSvgInfo, "Src", "http://192.168.0.1/i/allgood-icon.svg");
            Delay.Milliseconds(100);
            
            //Validate.ContainsImage(repo.WebDocumentIE.ConfirmWizard1.Http19216801IAllgoodIconSvgInfo, Http19216801IAllgoodIconSvg_Screenshot3, Http19216801IAllgoodIconSvg_Screenshot3_Options);
            //Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(19));
            
        }

#region Image Feature Data
        CompressedImage Button15_Screenshot1
        { get { return repo.WebDocument19216801.Button15Info.GetScreenshot1(new Rectangle(0, 0, 213, 56)); } }

        Imaging.FindOptions Button15_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Http19216801IAllgoodIconSvg_Screenshot3
        { get { return repo.WebDocumentIE.ConfirmWizard1.Http19216801IAllgoodIconSvgInfo.GetScreenshot3(new Rectangle(0, 0, 37, 37)); } }

        Imaging.FindOptions Http19216801IAllgoodIconSvg_Screenshot3_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
