///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace ArrisTest
{
    public partial class Change_5GHz_SSID_Name
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Validate_ErrCloseSSID50()
        {
            Validate.NotExists(repo.WebDocument19216801.ErrCloseSSID50Info);
        }

        public void Capture_5GHz_SSID_Name(string argument1)
        {
        	Report.Info("5GHz_SSID_Name : " + argument1);
        	Report.Screenshot(repo.WebDocument19216801.SSID50.Element,true);
        }

    }
}