///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Change_5GHz_SSID_Name recording.
    /// </summary>
    [TestModule("b8085a45-81ff-421f-9523-0dd33076bdec", ModuleType.Recording, 1)]
    public partial class Change_5GHz_SSID_Name : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Change_5GHz_SSID_Name instance = new Change_5GHz_SSID_Name();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Change_5GHz_SSID_Name()
        {
            SSID_Name_5GHz = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Change_5GHz_SSID_Name Instance
        {
            get { return instance; }
        }

#region Variables

        string _SSID_Name_5GHz;

        /// <summary>
        /// Gets or sets the value of variable SSID_Name_5GHz.
        /// </summary>
        [TestVariable("579a9724-9e08-4efc-8502-c02e59347c61")]
        public string SSID_Name_5GHz
        {
            get { return _SSID_Name_5GHz; }
            set { _SSID_Name_5GHz = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            repo.WebDocument19216801.SSID50.Click("71;5");
            Delay.Milliseconds(200);
            
            Keyboard.PrepareFocus(repo.WebDocument19216801.SSID50);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            repo.WebDocument19216801.SSID50.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
            repo.WebDocument19216801.SSID50.PressKeys(SSID_Name_5GHz);
            Delay.Milliseconds(0);
            
            //repo.WebDocument19216801.Button25.Click("59;37");
            //Delay.Milliseconds(200);
            
            //Validate.Attribute(repo.WebDocument19216801.ErrCloseSSID50Info, "Id", "errClose-SSID50");
            //Delay.Milliseconds(100);
            
            Capture_5GHz_SSID_Name(SSID_Name_5GHz);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
