///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace ArrisTest
{
    public partial class Check_5GHzPassword_Field
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Validate_Passphrase50()
        {
//        	String currentTestcaseName = TestCase.Current.Name;		//obsolete in 6.x
        	string currentTestcaseName = TestCaseNode.Current.Name;
        	
        	Report.Info("Current TC ", currentTestcaseName);
        	//check if the Passphrase50 field is enabled ?
//            Validate.Attribute(repo.WebDocument19216801.Passphrase50Info, "Enabled", "False");
			bool isEnabled = Validate.Attribute(repo.WebDocument19216801.Passphrase50Info, "Enabled", "True","{2}",false);
			if(isEnabled){
				Report.Success(" Passphrase50 is enabled !");
				if(currentTestcaseName.StartsWith("Validate_5GHz_Good_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Good_Password_Validation_Sec_Mode").Checked = true;
					TestSuite.Current.GetTestCase("Validate_Good_Pass_5GHz").Checked = true;	
				}else if(currentTestcaseName.StartsWith("Validate_5GHz_Strong_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Strong_Password_Validation_Sec_Mode").Checked = true;
					TestSuite.Current.GetTestCase("Validate_Strong_Pass_5GHz").Checked = true;
				}else if(currentTestcaseName.StartsWith("Validate_5GHz_Very_Strong_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Very_Strong_Pass_Validation_Sec_Mode").Checked = true;
					TestSuite.Current.GetTestCase("Validate_Very_Strong_Pass_5GHz").Checked = true;
				}else if(currentTestcaseName.StartsWith("Validate_5GHz_Not_Sufficient_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Not_Sufficient_Pass_Validation_Sec_Mode").Checked = true;
					TestSuite.Current.GetTestCase("Validate_Not_Sufficient_Pass_5GHz").Checked = true;					
				}else if(currentTestcaseName.StartsWith("Validate_5GHz_Invalid_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Invalid_Pass_Validation_Sec_Mode").Checked = true;
					TestSuite.Current.GetTestCase("Validate_Invalid_Pass_5GHz").Checked = true;					
				}
			}else{
				Report.Failure(" Passphrase50 is disabled !");
				if(currentTestcaseName.StartsWith("Validate_5GHz_Good_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Good_Password_Validation_Sec_Mode").Checked = false;
					TestSuite.Current.GetTestCase("Validate_Good_Pass_5GHz").Checked = false;
				}else if(currentTestcaseName.StartsWith("Validate_5GHz_Strong_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Strong_Password_Validation_Sec_Mode").Checked = false;
					TestSuite.Current.GetTestCase("Validate_Strong_Pass_5GHz").Checked = false;					
				}else if(currentTestcaseName.StartsWith("Validate_5GHz_Very_Strong_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Very_Strong_Pass_Validation_Sec_Mode").Checked = false;
					TestSuite.Current.GetTestCase("Validate_Very_Strong_Pass_5GHz").Checked = false;					
				}else if(currentTestcaseName.StartsWith("Validate_5GHz_Not_Sufficient_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Not_Sufficient_Pass_Validation_Sec_Mode").Checked = false;
					TestSuite.Current.GetTestCase("Validate_Not_Sufficient_Pass_5GHz").Checked = false;					
				}else if(currentTestcaseName.StartsWith("Validate_5GHz_Invalid_Password_Field")){
					TestSuite.Current.GetTestCase("Choose_5GHz_Primary_Invalid_Pass_Validation_Sec_Mode").Checked = false;
					TestSuite.Current.GetTestCase("Validate_Invalid_Pass_5GHz").Checked = false;					
				}
			}
			
        }

    }
}