///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Choose_Any_PortFiltering_To_Enable recording.
    /// </summary>
    [TestModule("cb7143ef-8ff4-4107-9cd6-c6399eb7bc64", ModuleType.Recording, 1)]
    public partial class Choose_Any_PortFiltering_To_Enable : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Choose_Any_PortFiltering_To_Enable instance = new Choose_Any_PortFiltering_To_Enable();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Choose_Any_PortFiltering_To_Enable()
        {
            SrsRangeStart_IP = "";
            SrcRangeEnd_IP = "";
            DstRangeStart_IP = "";
            DstRangeEnd_IP = "";
            SrcPortRange_Start = "";
            SrcPortRange_End = "";
            DstPortRange_Start = "";
            DstPortRange_End = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Choose_Any_PortFiltering_To_Enable Instance
        {
            get { return instance; }
        }

#region Variables

        string _SrsRangeStart_IP;

        /// <summary>
        /// Gets or sets the value of variable SrsRangeStart_IP.
        /// </summary>
        [TestVariable("8447de03-c355-45f5-9570-76e7730d9268")]
        public string SrsRangeStart_IP
        {
            get { return _SrsRangeStart_IP; }
            set { _SrsRangeStart_IP = value; }
        }

        string _SrcRangeEnd_IP;

        /// <summary>
        /// Gets or sets the value of variable SrcRangeEnd_IP.
        /// </summary>
        [TestVariable("6f732946-a816-4c8a-a826-59c1699b32ed")]
        public string SrcRangeEnd_IP
        {
            get { return _SrcRangeEnd_IP; }
            set { _SrcRangeEnd_IP = value; }
        }

        string _DstRangeStart_IP;

        /// <summary>
        /// Gets or sets the value of variable DstRangeStart_IP.
        /// </summary>
        [TestVariable("e756fe11-2893-4465-941c-6bf273afab20")]
        public string DstRangeStart_IP
        {
            get { return _DstRangeStart_IP; }
            set { _DstRangeStart_IP = value; }
        }

        string _DstRangeEnd_IP;

        /// <summary>
        /// Gets or sets the value of variable DstRangeEnd_IP.
        /// </summary>
        [TestVariable("8e2c7add-e0a5-4eac-990f-3a215b8ab015")]
        public string DstRangeEnd_IP
        {
            get { return _DstRangeEnd_IP; }
            set { _DstRangeEnd_IP = value; }
        }

        string _SrcPortRange_Start;

        /// <summary>
        /// Gets or sets the value of variable SrcPortRange_Start.
        /// </summary>
        [TestVariable("415171a4-6796-42e1-b7b2-b99f44b90e73")]
        public string SrcPortRange_Start
        {
            get { return _SrcPortRange_Start; }
            set { _SrcPortRange_Start = value; }
        }

        string _SrcPortRange_End;

        /// <summary>
        /// Gets or sets the value of variable SrcPortRange_End.
        /// </summary>
        [TestVariable("4e201b80-1058-4ad2-931d-40b88bbf982d")]
        public string SrcPortRange_End
        {
            get { return _SrcPortRange_End; }
            set { _SrcPortRange_End = value; }
        }

        string _DstPortRange_Start;

        /// <summary>
        /// Gets or sets the value of variable DstPortRange_Start.
        /// </summary>
        [TestVariable("91fca11f-61e3-42c9-a499-7c845f75f669")]
        public string DstPortRange_Start
        {
            get { return _DstPortRange_Start; }
            set { _DstPortRange_Start = value; }
        }

        string _DstPortRange_End;

        /// <summary>
        /// Gets or sets the value of variable DstPortRange_End.
        /// </summary>
        [TestVariable("4f1298bf-ca5d-447f-9440-3a8ec8c0ff02")]
        public string DstPortRange_End
        {
            get { return _DstPortRange_End; }
            set { _DstPortRange_End = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Choose_Any_IP4Port_Filtering_To_Enable(SrsRangeStart_IP, SrcRangeEnd_IP, DstRangeStart_IP, DstRangeEnd_IP, SrcPortRange_Start, SrcPortRange_End, DstPortRange_Start, DstPortRange_End);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
