///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Choose_IP_Port_Filtering_Rule_to_Delete recording.
    /// </summary>
    [TestModule("1f3f9e0e-9ca4-4117-a7de-f39b9a0f90cb", ModuleType.Recording, 1)]
    public partial class Choose_IP_Port_Filtering_Rule_to_Delete : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Choose_IP_Port_Filtering_Rule_to_Delete instance = new Choose_IP_Port_Filtering_Rule_to_Delete();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Choose_IP_Port_Filtering_Rule_to_Delete()
        {
            SourceRangeStart_IP = "";
            SourceRangeEnd_IP = "";
            DestRangeStart_IP = "";
            DestRangeEnd_IP = "";
            SourcePortRange_Start = "";
            SourcePortRange_End = "";
            DestPortRange_Start = "";
            DestPortRange_End = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Choose_IP_Port_Filtering_Rule_to_Delete Instance
        {
            get { return instance; }
        }

#region Variables

        string _SourceRangeStart_IP;

        /// <summary>
        /// Gets or sets the value of variable SourceRangeStart_IP.
        /// </summary>
        [TestVariable("5ec3dfdb-cb33-47ef-a9e1-00bfc89f386c")]
        public string SourceRangeStart_IP
        {
            get { return _SourceRangeStart_IP; }
            set { _SourceRangeStart_IP = value; }
        }

        string _SourceRangeEnd_IP;

        /// <summary>
        /// Gets or sets the value of variable SourceRangeEnd_IP.
        /// </summary>
        [TestVariable("393e807a-36e9-4d79-aca6-2990bbbacc97")]
        public string SourceRangeEnd_IP
        {
            get { return _SourceRangeEnd_IP; }
            set { _SourceRangeEnd_IP = value; }
        }

        string _DestRangeStart_IP;

        /// <summary>
        /// Gets or sets the value of variable DestRangeStart_IP.
        /// </summary>
        [TestVariable("86407684-06b5-41ab-89f2-7f8602bd17b2")]
        public string DestRangeStart_IP
        {
            get { return _DestRangeStart_IP; }
            set { _DestRangeStart_IP = value; }
        }

        string _DestRangeEnd_IP;

        /// <summary>
        /// Gets or sets the value of variable DestRangeEnd_IP.
        /// </summary>
        [TestVariable("59b8f154-b07a-459e-b9d5-037993d4b559")]
        public string DestRangeEnd_IP
        {
            get { return _DestRangeEnd_IP; }
            set { _DestRangeEnd_IP = value; }
        }

        string _SourcePortRange_Start;

        /// <summary>
        /// Gets or sets the value of variable SourcePortRange_Start.
        /// </summary>
        [TestVariable("8c1bc829-85af-4cb8-a0d2-38af587379d6")]
        public string SourcePortRange_Start
        {
            get { return _SourcePortRange_Start; }
            set { _SourcePortRange_Start = value; }
        }

        string _SourcePortRange_End;

        /// <summary>
        /// Gets or sets the value of variable SourcePortRange_End.
        /// </summary>
        [TestVariable("860b15f9-ffb2-4211-9e2b-50ef46463c88")]
        public string SourcePortRange_End
        {
            get { return _SourcePortRange_End; }
            set { _SourcePortRange_End = value; }
        }

        string _DestPortRange_Start;

        /// <summary>
        /// Gets or sets the value of variable DestPortRange_Start.
        /// </summary>
        [TestVariable("32286a8d-74cf-4c8e-b052-de81aee6b85d")]
        public string DestPortRange_Start
        {
            get { return _DestPortRange_Start; }
            set { _DestPortRange_Start = value; }
        }

        string _DestPortRange_End;

        /// <summary>
        /// Gets or sets the value of variable DestPortRange_End.
        /// </summary>
        [TestVariable("13d9d82b-b65c-474a-a4ff-ef5ed6c2f098")]
        public string DestPortRange_End
        {
            get { return _DestPortRange_End; }
            set { _DestPortRange_End = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Choose_IP_Port_Filter_Rules_to_Delete(SourceRangeStart_IP, SourceRangeEnd_IP, DestRangeStart_IP, DestRangeEnd_IP, SourcePortRange_Start, SourcePortRange_End, DestPortRange_Start, DestPortRange_End);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
