///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Choose_Any_MAC_Filter_Devices recording.
    /// </summary>
    [TestModule("85b5d816-9f34-41df-8266-25b5bc01d6db", ModuleType.Recording, 1)]
    public partial class Choose_Any_MAC_Filter_Devices : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Choose_Any_MAC_Filter_Devices instance = new Choose_Any_MAC_Filter_Devices();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Choose_Any_MAC_Filter_Devices()
        {
            MACAddress_0 = "";
            MACAddress_1 = "";
            MACAddress_2 = "";
            MACAddress_3 = "";
            MACAddress_4 = "";
            MACAddress_5 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Choose_Any_MAC_Filter_Devices Instance
        {
            get { return instance; }
        }

#region Variables

        string _MACAddress_0;

        /// <summary>
        /// Gets or sets the value of variable MACAddress_0.
        /// </summary>
        [TestVariable("a6a113b5-08bd-4e81-8d2a-35363f6c6353")]
        public string MACAddress_0
        {
            get { return _MACAddress_0; }
            set { _MACAddress_0 = value; }
        }

        string _MACAddress_1;

        /// <summary>
        /// Gets or sets the value of variable MACAddress_1.
        /// </summary>
        [TestVariable("fba3c6d6-783d-4b16-b8d4-3503247d7b17")]
        public string MACAddress_1
        {
            get { return _MACAddress_1; }
            set { _MACAddress_1 = value; }
        }

        string _MACAddress_2;

        /// <summary>
        /// Gets or sets the value of variable MACAddress_2.
        /// </summary>
        [TestVariable("2ffe832e-620e-4e12-9a03-b3ee3065ac2c")]
        public string MACAddress_2
        {
            get { return _MACAddress_2; }
            set { _MACAddress_2 = value; }
        }

        string _MACAddress_3;

        /// <summary>
        /// Gets or sets the value of variable MACAddress_3.
        /// </summary>
        [TestVariable("b965cada-b11a-4770-b46a-7c3134627cd1")]
        public string MACAddress_3
        {
            get { return _MACAddress_3; }
            set { _MACAddress_3 = value; }
        }

        string _MACAddress_4;

        /// <summary>
        /// Gets or sets the value of variable MACAddress_4.
        /// </summary>
        [TestVariable("46b46f34-df38-4d61-afcd-05edfbc9d112")]
        public string MACAddress_4
        {
            get { return _MACAddress_4; }
            set { _MACAddress_4 = value; }
        }

        string _MACAddress_5;

        /// <summary>
        /// Gets or sets the value of variable MACAddress_5.
        /// </summary>
        [TestVariable("a2c04464-7d29-4766-a4f1-835ca9532b87")]
        public string MACAddress_5
        {
            get { return _MACAddress_5; }
            set { _MACAddress_5 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Choose_Any_MAC_Filtering_Device_To_Delete(MACAddress_0, MACAddress_1, MACAddress_2, MACAddress_3, MACAddress_4, MACAddress_5);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
