///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Choose_Any_5Ghz_Wireless_MAC_Filter_Device recording.
    /// </summary>
    [TestModule("a464276e-ab10-45cf-9699-a0520f4d7db7", ModuleType.Recording, 1)]
    public partial class Choose_Any_5Ghz_Wireless_MAC_Filter_Device : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Choose_Any_5Ghz_Wireless_MAC_Filter_Device instance = new Choose_Any_5Ghz_Wireless_MAC_Filter_Device();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Choose_Any_5Ghz_Wireless_MAC_Filter_Device()
        {
            DeviceName_5GHz = "";
            MAC0_5GHz = "";
            MAC1_5GHz = "";
            MAC2_5GHz = "";
            MAC3_5GHz = "";
            MAC4_5GHz = "";
            MAC5_5GHz = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Choose_Any_5Ghz_Wireless_MAC_Filter_Device Instance
        {
            get { return instance; }
        }

#region Variables

        string _DeviceName_5GHz;

        /// <summary>
        /// Gets or sets the value of variable DeviceName_5GHz.
        /// </summary>
        [TestVariable("559e65c2-9841-4259-a83d-ce0fbe363f37")]
        public string DeviceName_5GHz
        {
            get { return _DeviceName_5GHz; }
            set { _DeviceName_5GHz = value; }
        }

        string _MAC0_5GHz;

        /// <summary>
        /// Gets or sets the value of variable MAC0_5GHz.
        /// </summary>
        [TestVariable("47a7148b-9511-43c0-8081-7b2c67a7a738")]
        public string MAC0_5GHz
        {
            get { return _MAC0_5GHz; }
            set { _MAC0_5GHz = value; }
        }

        string _MAC1_5GHz;

        /// <summary>
        /// Gets or sets the value of variable MAC1_5GHz.
        /// </summary>
        [TestVariable("dff6a91f-9f25-4eb2-ae88-5351eaf1e4e8")]
        public string MAC1_5GHz
        {
            get { return _MAC1_5GHz; }
            set { _MAC1_5GHz = value; }
        }

        string _MAC2_5GHz;

        /// <summary>
        /// Gets or sets the value of variable MAC2_5GHz.
        /// </summary>
        [TestVariable("dc9d6a8d-de19-49cb-92fd-f3f66f8614c5")]
        public string MAC2_5GHz
        {
            get { return _MAC2_5GHz; }
            set { _MAC2_5GHz = value; }
        }

        string _MAC3_5GHz;

        /// <summary>
        /// Gets or sets the value of variable MAC3_5GHz.
        /// </summary>
        [TestVariable("b8a46a1f-605f-4d4a-a3f9-c7edb32faa66")]
        public string MAC3_5GHz
        {
            get { return _MAC3_5GHz; }
            set { _MAC3_5GHz = value; }
        }

        string _MAC4_5GHz;

        /// <summary>
        /// Gets or sets the value of variable MAC4_5GHz.
        /// </summary>
        [TestVariable("0c2f5b19-d8bf-4eca-8a59-93155f3e7699")]
        public string MAC4_5GHz
        {
            get { return _MAC4_5GHz; }
            set { _MAC4_5GHz = value; }
        }

        string _MAC5_5GHz;

        /// <summary>
        /// Gets or sets the value of variable MAC5_5GHz.
        /// </summary>
        [TestVariable("37bd4600-a76d-4ed2-8c13-aec2c5d401ea")]
        public string MAC5_5GHz
        {
            get { return _MAC5_5GHz; }
            set { _MAC5_5GHz = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Choose_Any_5GHz_Wireless_MAC_Filtering_Device_To_Delete(MAC0_5GHz, MAC1_5GHz, MAC2_5GHz, MAC3_5GHz, MAC4_5GHz, MAC5_5GHz, DeviceName_5GHz);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
