///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Choose_First_Port_Fwd_Rule_To_Disable recording.
    /// </summary>
    [TestModule("06e25982-ec63-4b49-9249-05c52e4e0fdc", ModuleType.Recording, 1)]
    public partial class Choose_First_Port_Fwd_Rule_To_Disable : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Choose_First_Port_Fwd_Rule_To_Disable instance = new Choose_First_Port_Fwd_Rule_To_Disable();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Choose_First_Port_Fwd_Rule_To_Disable()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Choose_First_Port_Fwd_Rule_To_Disable Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //repo.WebDocumentIE.Self.MoveTo("1355;89");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //repo.WebDocumentIE.Self.MoveTo("1344;381");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //repo.WebDocumentIE.FmCbxFm01.Click("9;15");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'WebDocumentIE.FmCbxFm01'.", repo.WebDocumentIE.FmCbxFm01Info, new RecordItemIndex(3));
            //Validate.Attribute(repo.WebDocumentIE.FmCbxFm01Info, "Enabled", "True");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='fmCheckbox checked') on item 'WebDocumentIE.FmCbxFm01'.", repo.WebDocumentIE.FmCbxFm01Info, new RecordItemIndex(4));
            //Validate.Attribute(repo.WebDocumentIE.FmCbxFm01Info, "Class", "fmCheckbox checked");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='fmCbx-fm-0-1') on item 'WebDocumentIE.FmCbxFm01'.", repo.WebDocumentIE.FmCbxFm01Info, new RecordItemIndex(5));
            //Validate.Attribute(repo.WebDocumentIE.FmCbxFm01Info, "Id", "fmCbx-fm-0-1");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=26,Height=26}) on item 'WebDocumentIE.FmCbxFm01'.", repo.WebDocumentIE.FmCbxFm01Info, new RecordItemIndex(6));
            //Validate.ContainsImage(repo.WebDocumentIE.FmCbxFm01Info, FmCbxFm01_Screenshot1, FmCbxFm01_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmChbxPortTriggeringTableEnabled0' at 11;13.", repo.WebDocument19216801.FmChbxPortTriggeringTableEnabled0Info, new RecordItemIndex(7));
            //repo.WebDocument19216801.FmChbxPortTriggeringTableEnabled0.Click("11;13");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmChbxPortTriggeringTableEnabled1' at 17;18.", repo.WebDocument19216801.FmChbxPortTriggeringTableEnabled1Info, new RecordItemIndex(8));
            //repo.WebDocument19216801.FmChbxPortTriggeringTableEnabled1.Click("17;18");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIE.DeleteApply' at 70;30.", repo.WebDocumentIE.DeleteApplyInfo, new RecordItemIndex(9));
            //repo.WebDocumentIE.DeleteApply.Click("70;30");
            //Delay.Milliseconds(200);
            
            check_If_Enable_Checkbox_Visible();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmChbxPortTriggeringTableEnabled0' at 13;9.", repo.WebDocument19216801.FmChbxPortTriggeringTableEnabled0Info, new RecordItemIndex(11));
            repo.WebDocument19216801.FmChbxPortTriggeringTableEnabled0.Click("13;9");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIE.DeleteApply' at 104;30.", repo.WebDocumentIE.DeleteApplyInfo, new RecordItemIndex(12));
            //repo.WebDocumentIE.DeleteApply.Click("104;30");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage FmCbxFm01_Screenshot1
        { get { return repo.WebDocumentIE.FmCbxFm01Info.GetScreenshot1(new Rectangle(0, 0, 26, 26)); } }

        Imaging.FindOptions FmCbxFm01_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
