///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Choose_Wireless_Mode_2GHz recording.
    /// </summary>
    [TestModule("5888b92a-ae01-4ebe-a254-cff0d3112ece", ModuleType.Recording, 1)]
    public partial class Choose_Wireless_Mode_2GHz : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Choose_Wireless_Mode_2GHz instance = new Choose_Wireless_Mode_2GHz();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Choose_Wireless_Mode_2GHz()
        {
            Wireless_Mode_2GHz = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Choose_Wireless_Mode_2GHz Instance
        {
            get { return instance; }
        }

#region Variables

        string _Wireless_Mode_2GHz;

        /// <summary>
        /// Gets or sets the value of variable Wireless_Mode_2GHz.
        /// </summary>
        [TestVariable("e56dff8b-4147-4a46-bb57-9e230a35fa8a")]
        public string Wireless_Mode_2GHz
        {
            get { return _Wireless_Mode_2GHz; }
            set { _Wireless_Mode_2GHz = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Wireless_Mode__Selection_2GHz(Wireless_Mode_2GHz);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
