///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Close_WiFi_Connection_Password_Config_Screen recording.
    /// </summary>
    [TestModule("ede93ced-8ea1-4a2e-9ce8-22b36047745c", ModuleType.Recording, 1)]
    public partial class Close_WiFi_Connection_Password_Config_Screen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Close_WiFi_Connection_Password_Config_Screen instance = new Close_WiFi_Connection_Password_Config_Screen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Close_WiFi_Connection_Password_Config_Screen()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Close_WiFi_Connection_Password_Config_Screen Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Validate.Attribute(repo.WebDocument19216801.WiFiNetworkFrame1.Button26Info, "Class", "wizard_button");
            Delay.Milliseconds(100);
            
            Validate.Attribute(repo.WebDocument19216801.WiFiNetworkFrame1.Button26Info, "TagValue", "Close");
            Delay.Milliseconds(100);
            
            Validate.Attribute(repo.WebDocument19216801.WiFiNetworkFrame1.Button26Info, "Value", "Close");
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(3));
            
            repo.WebDocument19216801.WiFiNetworkFrame1.Button26.Click("71;27");
            Delay.Milliseconds(200);
            
            repo.WebDocumentIE.Close.Click("54;31");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
