///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
// 
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;

namespace ArrisTest
{
    public partial class Count_Reservation_List
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void Count_List_Of_Reserv_List()
        {
			Delay.Seconds(30);
        	WebDocument webDocument = "/dom[@domain='192.168.0.1']";
        	webDocument.WaitForDocumentLoaded();
        	TableTag myTable = webDocument.FindSingle("/dom[@domain='192.168.0.1']//table[#'dhcpClientsTable']");
        	IList<TrTag> rows = myTable.Find<TrTag>("./tbody//tr");
            int rowsCnt = rows.Count;
            Report.Info("Total Reservation_List",rowsCnt.ToString());
            if(rowsCnt == 32){
            	 Report.Info("Total Reservation_List",rowsCnt.ToString());
            	 TestSuite.Current.GetTestCase("DHCP_Reservation_Add_Rule1").Checked = true;
            }else if(rowsCnt < 32){
            	 Report.Info("Total No of Reservation_List is less than 32");
            	 TestSuite.Current.GetTestCase("DHCP_Reservation_Add_Rule1").Checked = false;
            }else{
            	Report.Info("Total No of Reservation_List is more than 32");
            	TestSuite.Current.GetTestCase("DHCP_Reservation_Add_Rule1").Checked = false;
            }        	
        }

    }
}