///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Edit_Guest_Network_Password_From_HomeScreen recording.
    /// </summary>
    [TestModule("7e3f30d1-82b6-4b09-a6a3-e78d83a145fd", ModuleType.Recording, 1)]
    public partial class Edit_Guest_Network_Password_From_HomeScreen : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Edit_Guest_Network_Password_From_HomeScreen instance = new Edit_Guest_Network_Password_From_HomeScreen();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Edit_Guest_Network_Password_From_HomeScreen()
        {
            New_Guest_Password = "Changeme12";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Edit_Guest_Network_Password_From_HomeScreen Instance
        {
            get { return instance; }
        }

#region Variables

        string _New_Guest_Password;

        /// <summary>
        /// Gets or sets the value of variable New_Guest_Password.
        /// </summary>
        [TestVariable("bbdaf659-93bd-40ed-9d07-98643ec8a2ae")]
        public string New_Guest_Password
        {
            get { return _New_Guest_Password; }
            set { _New_Guest_Password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            repo.WebDocument19216801.ModifyYourGuestNetwork.Click("95;16");
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(1));
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Modify Your Guest Network') on item 'WebDocument19216801.ModifyYourGuestNetwork1'.", repo.WebDocument19216801.ModifyYourGuestNetwork1Info, new RecordItemIndex(2));
            //Validate.Attribute(repo.WebDocument19216801.ModifyYourGuestNetwork1Info, "InnerText", "Modify Your Guest Network");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.ModifyYourGuestNetwork1' at 114;23.", repo.WebDocument19216801.ModifyYourGuestNetwork1Info, new RecordItemIndex(3));
            //repo.WebDocument19216801.ModifyYourGuestNetwork1.Click("114;23");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Guest network') on item 'WebDocument19216801.GuestNetwork'.", repo.WebDocument19216801.GuestNetworkInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.WebDocument19216801.GuestNetworkInfo, "InnerText", "Guest network");
            Delay.Milliseconds(100);
            
            //repo.WebDocument19216801.FmRbtnEditGuestNetwork.Click("12;12");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='wizard_checkbox guest_wizard_checkbox_setting') on item 'WebDocument19216801.TrEditGuestNetwork'.", repo.WebDocument19216801.TrEditGuestNetworkInfo, new RecordItemIndex(6));
            //Validate.Attribute(repo.WebDocument19216801.TrEditGuestNetworkInfo, "Class", "wizard_checkbox guest_wizard_checkbox_setting");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='tr_EditGuestNetwork') on item 'WebDocument19216801.TrEditGuestNetwork'.", repo.WebDocument19216801.TrEditGuestNetworkInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.WebDocument19216801.TrEditGuestNetworkInfo, "Id", "tr_EditGuestNetwork");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=431,Height=68}) on item 'WebDocument19216801.TrEditGuestNetwork'.", repo.WebDocument19216801.TrEditGuestNetworkInfo, new RecordItemIndex(8));
            //Validate.ContainsImage(repo.WebDocument19216801.TrEditGuestNetworkInfo, TrEditGuestNetwork_Screenshot1, TrEditGuestNetwork_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmChbxEditGuestNetwork' at 15;20.", repo.WebDocument19216801.FmChbxEditGuestNetworkInfo, new RecordItemIndex(9));
            repo.WebDocument19216801.FmChbxEditGuestNetwork.Click("15;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='fmCheckbox checked') on item 'WebDocument19216801.FmChbxEditGuestNetwork'.", repo.WebDocument19216801.FmChbxEditGuestNetworkInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.WebDocument19216801.FmChbxEditGuestNetworkInfo, "Class", "fmCheckbox checked");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='fmChbx-EditGuestNetwork') on item 'WebDocument19216801.FmChbxEditGuestNetwork'.", repo.WebDocument19216801.FmChbxEditGuestNetworkInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.WebDocument19216801.FmChbxEditGuestNetworkInfo, "Id", "fmChbx-EditGuestNetwork");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=31,Height=31}) on item 'WebDocument19216801.FmChbxEditGuestNetwork'.", repo.WebDocument19216801.FmChbxEditGuestNetworkInfo, new RecordItemIndex(12));
            //Validate.ContainsImage(repo.WebDocument19216801.FmChbxEditGuestNetworkInfo, FmChbxEditGuestNetwork_Screenshot1, FmChbxEditGuestNetwork_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(13));
            
            repo.WebDocument19216801.GuestApplyOrNext.Click("44;26");
            Delay.Milliseconds(200);
            
            repo.WebDocument19216801.Change1.Click("17;18");
            Delay.Milliseconds(200);
            
            repo.WebDocument19216801.NewPassphrase.Click("52;9");
            Delay.Milliseconds(200);
            
            Keyboard.PrepareFocus(repo.WebDocument19216801.NewPassphrase);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Keyboard.PrepareFocus(repo.WebDocument19216801.NewPassphrase);
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            repo.WebDocument19216801.NewPassphrase.PressKeys(New_Guest_Password);
            Delay.Milliseconds(0);
            
            //Validate.Attribute(repo.WebDocument19216801.PasstextWifiInfo, "InnerText", "Good");
            //Delay.Milliseconds(100);
            
            Validate_PasstextWifi(New_Guest_Password);
            Delay.Milliseconds(0);
            
            repo.WebDocument19216801.Button2.Click("84;18");
            Delay.Milliseconds(200);
            
            //Validate.Attribute(repo.WebDocument19216801.EnableGuestBtnInfo, "TagValue", "Next");
            //Delay.Milliseconds(100);
            
            //repo.WebDocument19216801.EnableGuestBtn.Click("82;30");
            //Delay.Milliseconds(200);
            
            //repo.WebDocument19216801.EnableGuestBtn.Click();
            //Delay.Milliseconds(200);
            
            //repo.WebDocument19216801.Button3.Click("80;39");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='How long would you like your guest network to beenabled?') on item 'WebDocument19216801.GuestNetworkFrame3.HowLongWouldYouLikeYourGuestNetwo'.", repo.WebDocument19216801.GuestNetworkFrame3.HowLongWouldYouLikeYourGuestNetwoInfo, new RecordItemIndex(27));
            //Validate.Attribute(repo.WebDocument19216801.GuestNetworkFrame3.HowLongWouldYouLikeYourGuestNetwoInfo, "InnerText", "How long would you like your guest network to beenabled?");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='At what times would you like your guest network to be enabled?') on item 'WebDocument19216801.GuestNetworkFrame3.AtWhatTimesWouldYouLikeYourGuest'.", repo.WebDocument19216801.GuestNetworkFrame3.AtWhatTimesWouldYouLikeYourGuestInfo, new RecordItemIndex(28));
            //Validate.Attribute(repo.WebDocument19216801.GuestNetworkFrame3.AtWhatTimesWouldYouLikeYourGuestInfo, "InnerText", "At what times would you like your guest network to be enabled?");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='At what times would you like your guest network to beenabled?') on item 'WebDocument19216801.GuestNetworkFrame3.AtWhatTimesWouldYouLikeYourGuest'.", repo.WebDocument19216801.GuestNetworkFrame3.AtWhatTimesWouldYouLikeYourGuestInfo, new RecordItemIndex(29));
            Validate.Attribute(repo.WebDocument19216801.GuestNetworkFrame3.AtWhatTimesWouldYouLikeYourGuestInfo, "InnerText", "At what times would you like your guest network to beenabled?");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.GuestNetworkFrame3.Button' at 115;26.", repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, new RecordItemIndex(30));
            //repo.WebDocument19216801.GuestNetworkFrame3.Button.MoveTo("115;26");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.GuestNetworkFrame3.Button' at 115;26.", repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, new RecordItemIndex(31));
            //repo.WebDocument19216801.GuestNetworkFrame3.Button.MoveTo("115;26");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Button26' at 64;27.", repo.WebDocument19216801.Button26Info, new RecordItemIndex(32));
            //repo.WebDocument19216801.Button26.Click("64;27");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Always on') on item 'WebDocument19216801.AlwaysOn'.", repo.WebDocument19216801.AlwaysOnInfo, new RecordItemIndex(33));
            Validate.Attribute(repo.WebDocument19216801.AlwaysOnInfo, "InnerText", "Always on");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='fmRadio checked') on item 'WebDocument19216801.FmRbtnGuestAlways'.", repo.WebDocument19216801.FmRbtnGuestAlwaysInfo, new RecordItemIndex(34));
            Validate.Attribute(repo.WebDocument19216801.FmRbtnGuestAlwaysInfo, "Class", "fmRadio checked");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='fmRbtn-GuestAlways') on item 'WebDocument19216801.FmRbtnGuestAlways'.", repo.WebDocument19216801.FmRbtnGuestAlwaysInfo, new RecordItemIndex(35));
            Validate.Attribute(repo.WebDocument19216801.FmRbtnGuestAlwaysInfo, "Id", "fmRbtn-GuestAlways");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=31,Height=31}) on item 'WebDocument19216801.FmRbtnGuestAlways'.", repo.WebDocument19216801.FmRbtnGuestAlwaysInfo, new RecordItemIndex(36));
            //Validate.ContainsImage(repo.WebDocument19216801.FmRbtnGuestAlwaysInfo, FmRbtnGuestAlways_Screenshot1, FmRbtnGuestAlways_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "Edit Guest Network", null, false, new RecordItemIndex(37));
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.GuestNetworkFrame3.Button' at 173;38.", repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, new RecordItemIndex(38));
            //repo.WebDocument19216801.GuestNetworkFrame3.Button.Click("173;38");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='Back') on item 'WebDocument19216801.GuestNetworkFrame3.Button6'.", repo.WebDocument19216801.GuestNetworkFrame3.Button6Info, new RecordItemIndex(39));
            Validate.Attribute(repo.WebDocument19216801.GuestNetworkFrame3.Button6Info, "TagValue", "Back");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Back') on item 'WebDocument19216801.GuestNetworkFrame3.Button6'.", repo.WebDocument19216801.GuestNetworkFrame3.Button6Info, new RecordItemIndex(40));
            Validate.Attribute(repo.WebDocument19216801.GuestNetworkFrame3.Button6Info, "Value", "Back");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='wizard_button') on item 'WebDocument19216801.GuestNetworkFrame3.Button'.", repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, new RecordItemIndex(41));
            Validate.Attribute(repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, "Class", "wizard_button");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='Apply changes') on item 'WebDocument19216801.GuestNetworkFrame3.Button'.", repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, new RecordItemIndex(42));
            Validate.Attribute(repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, "TagValue", "Apply changes");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Apply changes') on item 'WebDocument19216801.GuestNetworkFrame3.Button'.", repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, new RecordItemIndex(43));
            Validate.Attribute(repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, "Value", "Apply changes");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.GuestNetworkFrame3.Button' at 120;24.", repo.WebDocument19216801.GuestNetworkFrame3.ButtonInfo, new RecordItemIndex(44));
            repo.WebDocument19216801.GuestNetworkFrame3.Button.Click("120;24");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Your guest network settings have been updated.') on item 'WebDocument19216801.YourGuestNetworkSettingsHaveBeenUp'.", repo.WebDocument19216801.YourGuestNetworkSettingsHaveBeenUpInfo, new RecordItemIndex(45));
            //Validate.Attribute(repo.WebDocument19216801.YourGuestNetworkSettingsHaveBeenUpInfo, "InnerText", "Your guest network settings have been updated.");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Button26' at 68;36.", repo.WebDocument19216801.Button26Info, new RecordItemIndex(46));
            //repo.WebDocument19216801.Button26.Click("68;36");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Your guest network settings have been updated.') on item 'WebDocument19216801.YourGuestNetworkSettingsHaveBeenUp'.", repo.WebDocument19216801.YourGuestNetworkSettingsHaveBeenUpInfo, new RecordItemIndex(47));
            Validate.Attribute(repo.WebDocument19216801.YourGuestNetworkSettingsHaveBeenUpInfo, "InnerText", "Your guest network settings have been updated.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='circle') on item 'WebDocument19216801.Circle'.", repo.WebDocument19216801.CircleInfo, new RecordItemIndex(48));
            Validate.Attribute(repo.WebDocument19216801.CircleInfo, "TagName", "circle");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=58,Height=57}) on item 'WebDocument19216801.Circle'.", repo.WebDocument19216801.CircleInfo, new RecordItemIndex(49));
            //Validate.ContainsImage(repo.WebDocument19216801.CircleInfo, Circle_Screenshot1, Circle_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "Edit Guest Network", null, false, new RecordItemIndex(50));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Button26' at 80;36.", repo.WebDocument19216801.Button26Info, new RecordItemIndex(51));
            repo.WebDocument19216801.Button26.Click("80;36");
            Delay.Milliseconds(200);
            
            //Validate.Attribute(repo.WebDocument19216801.Button4Info, "TagValue", "Finish");
            //Delay.Milliseconds(100);
            
            //repo.WebDocument19216801.Button4.Click();
            //Delay.Milliseconds(200);
            
            //Delay.Duration(1000, false);
            
        }

#region Image Feature Data
        CompressedImage TrEditGuestNetwork_Screenshot1
        { get { return repo.WebDocument19216801.TrEditGuestNetworkInfo.GetScreenshot1(new Rectangle(0, 0, 431, 68)); } }

        Imaging.FindOptions TrEditGuestNetwork_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage FmChbxEditGuestNetwork_Screenshot1
        { get { return repo.WebDocument19216801.FmChbxEditGuestNetworkInfo.GetScreenshot1(new Rectangle(0, 0, 31, 31)); } }

        Imaging.FindOptions FmChbxEditGuestNetwork_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage FmRbtnGuestAlways_Screenshot1
        { get { return repo.WebDocument19216801.FmRbtnGuestAlwaysInfo.GetScreenshot1(new Rectangle(0, 0, 31, 31)); } }

        Imaging.FindOptions FmRbtnGuestAlways_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Circle_Screenshot1
        { get { return repo.WebDocument19216801.CircleInfo.GetScreenshot1(new Rectangle(0, 0, 58, 57)); } }

        Imaging.FindOptions Circle_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
