///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Guest_2_4GHz_Change_Password recording.
    /// </summary>
    [TestModule("ca0d5c84-74ab-48a1-b66c-583798fe3030", ModuleType.Recording, 1)]
    public partial class Guest_2_4GHz_Change_Password : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Guest_2_4GHz_Change_Password instance = new Guest_2_4GHz_Change_Password();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Guest_2_4GHz_Change_Password()
        {
            Guest_Pass = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Guest_2_4GHz_Change_Password Instance
        {
            get { return instance; }
        }

#region Variables

        string _Guest_Pass;

        /// <summary>
        /// Gets or sets the value of variable Guest_Pass.
        /// </summary>
        [TestVariable("b353f214-b18f-47d6-8704-67398666fcec")]
        public string Guest_Pass
        {
            get { return _Guest_Pass; }
            set { _Guest_Pass = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.WebDocument19216801' at 1359;269.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(0));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1359;269");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Passphrase' at Center.", repo.WebDocument19216801.PassphraseInfo, new RecordItemIndex(1));
            //repo.WebDocument19216801.Passphrase.Click();
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press.", new RecordItemIndex(2));
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Delete' Press.", new RecordItemIndex(3));
            //Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Guest_Pass' with focus on 'WebDocument19216801.Passphrase'.", repo.WebDocument19216801.PassphraseInfo, new RecordItemIndex(4));
            //repo.WebDocument19216801.Passphrase.PressKeys(Guest_Pass);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1358;408.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(5));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1358;408");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey up}'.", new RecordItemIndex(6));
            //Keyboard.Press("{LControlKey up}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(7));
            //Validate.Attribute(repo.WebDocument19216801.Button7Info, "Visible", "True");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='submitBtn') on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(8));
            //Validate.Attribute(repo.WebDocument19216801.Button7Info, "Class", "submitBtn");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='Apply changes') on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(9));
            //Validate.Attribute(repo.WebDocument19216801.Button7Info, "TagValue", "Apply changes");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Apply changes') on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(10));
            //Validate.Attribute(repo.WebDocument19216801.Button7Info, "Value", "Apply changes");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=166,Height=43}) on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(11));
            //Validate.ContainsImage(repo.WebDocument19216801.Button7Info, Button7_Screenshot2, Button7_Screenshot2_Options);
            //Delay.Milliseconds(100);
            
            Validate_Disable_GuestNetwork();
            Delay.Milliseconds(0);
            
            repo.WebDocument19216801.Button7.Click("99;20");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey up}'.", new RecordItemIndex(14));
            //Keyboard.Press("{LControlKey up}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.LogOut' at 30;3.", repo.WebDocument19216801.LogOutInfo, new RecordItemIndex(15));
            //repo.WebDocument19216801.LogOut.Click("30;3");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey up}'.", new RecordItemIndex(16));
            //Keyboard.Press("{LControlKey up}");
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage Button7_Screenshot2
        { get { return repo.WebDocument19216801.Button7Info.GetScreenshot2(new Rectangle(0, 0, 166, 43)); } }

        Imaging.FindOptions Button7_Screenshot2_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
