///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Guest_Good_Password_Validation_5GHz_Recording recording.
    /// </summary>
    [TestModule("b2fabaea-8c87-41d4-8d83-bd20fd12312e", ModuleType.Recording, 1)]
    public partial class Guest_Good_Password_Validation_5GHz_Recording : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Guest_Good_Password_Validation_5GHz_Recording instance = new Guest_Good_Password_Validation_5GHz_Recording();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Guest_Good_Password_Validation_5GHz_Recording()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Guest_Good_Password_Validation_5GHz_Recording Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (HasFocus='False') on item 'WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4'.", repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, new RecordItemIndex(0));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, "HasFocus", "False");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4'.", repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, new RecordItemIndex(1));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=193,Height=28}) on item 'WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4'.", repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, new RecordItemIndex(2));
            Validate.ContainsImage(repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, SomeSpanTag4_Screenshot1, SomeSpanTag4_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Disable') on item 'WebDocument19216801.FmSelSecurityModeGrp.Disable2'.", repo.WebDocument19216801.FmSelSecurityModeGrp.Disable2Info, new RecordItemIndex(3));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.Disable2Info, "InnerText", "Disable");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='cite') on item 'WebDocument19216801.FmSelSecurityModeGrp.Disable2'.", repo.WebDocument19216801.FmSelSecurityModeGrp.Disable2Info, new RecordItemIndex(4));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.Disable2Info, "TagName", "cite");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=177,Height=32}) on item 'WebDocument19216801.FmSelSecurityModeGrp.Disable2'.", repo.WebDocument19216801.FmSelSecurityModeGrp.Disable2Info, new RecordItemIndex(5));
            Validate.ContainsImage(repo.WebDocument19216801.FmSelSecurityModeGrp.Disable2Info, Disable2_Screenshot1, Disable2_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4' at 180;20.", repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, new RecordItemIndex(6));
            repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4.Click("180;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4' at 179;13.", repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, new RecordItemIndex(7));
            repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4.Click("179;13");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Fm0' at 861;456.", repo.WebDocument19216801.Fm0Info, new RecordItemIndex(8));
            repo.WebDocument19216801.Fm0.Click("861;456");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.FmSelSecurityModeGrp.WPA2PSK'.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSKInfo, new RecordItemIndex(9));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSKInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='WPA2-PSK') on item 'WebDocument19216801.FmSelSecurityModeGrp.WPA2PSK'.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSKInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSKInfo, "InnerText", "WPA2-PSK");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='cite') on item 'WebDocument19216801.FmSelSecurityModeGrp.WPA2PSK'.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSKInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSKInfo, "TagName", "cite");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=177,Height=32}) on item 'WebDocument19216801.FmSelSecurityModeGrp.WPA2PSK'.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSKInfo, new RecordItemIndex(12));
            Validate.ContainsImage(repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSKInfo, WPA2PSK_Screenshot1, WPA2PSK_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4' at 182;15.", repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, new RecordItemIndex(13));
            repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4.Click("182;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4' at 181;15.", repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, new RecordItemIndex(14));
            repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4.Click("181;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK' at 142;12.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSKInfo, new RecordItemIndex(15));
            repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK.Click("142;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1'.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1Info, new RecordItemIndex(16));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='WPA-PSK/WPA2-PSK') on item 'WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1'.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1Info, new RecordItemIndex(17));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1Info, "InnerText", "WPA-PSK/WPA2-PSK");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='cite') on item 'WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1'.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1Info, new RecordItemIndex(18));
            Validate.Attribute(repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1Info, "TagName", "cite");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=177,Height=32}) on item 'WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1'.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1Info, new RecordItemIndex(19));
            Validate.ContainsImage(repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1Info, WPAPSKWPA2PSK1_Screenshot1, WPAPSKWPA2PSK1_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmInpPassphrase' at 184;36.", repo.WebDocument19216801.FmInpPassphraseInfo, new RecordItemIndex(20));
            repo.WebDocument19216801.FmInpPassphrase.Click("184;36");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Enabled='True') on item 'WebDocument19216801.Passphrase'.", repo.WebDocument19216801.PassphraseInfo, new RecordItemIndex(21));
            Validate.Attribute(repo.WebDocument19216801.PassphraseInfo, "Enabled", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='Passphrase') on item 'WebDocument19216801.Passphrase'.", repo.WebDocument19216801.PassphraseInfo, new RecordItemIndex(22));
            Validate.Attribute(repo.WebDocument19216801.PassphraseInfo, "Id", "Passphrase");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='input') on item 'WebDocument19216801.Passphrase'.", repo.WebDocument19216801.PassphraseInfo, new RecordItemIndex(23));
            Validate.Attribute(repo.WebDocument19216801.PassphraseInfo, "TagName", "input");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='amm1nOTe5ting') on item 'WebDocument19216801.Passphrase'.", repo.WebDocument19216801.PassphraseInfo, new RecordItemIndex(24));
            Validate.Attribute(repo.WebDocument19216801.PassphraseInfo, "TagValue", "amm1nOTe5ting");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='amm1nOTe5ting') on item 'WebDocument19216801.Passphrase'.", repo.WebDocument19216801.PassphraseInfo, new RecordItemIndex(25));
            Validate.Attribute(repo.WebDocument19216801.PassphraseInfo, "Value", "amm1nOTe5ting");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot3' with region {X=0,Y=0,Width=213,Height=20}) on item 'WebDocument19216801.Passphrase'.", repo.WebDocument19216801.PassphraseInfo, new RecordItemIndex(26));
            Validate.ContainsImage(repo.WebDocument19216801.PassphraseInfo, Passphrase_Screenshot3, Passphrase_Screenshot3_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4' at 184;21.", repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info, new RecordItemIndex(27));
            repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4.Click("184;21");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.FmSelSecurityModeGrp.WPA2PSK1' at 79;15.", repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSK1Info, new RecordItemIndex(28));
            repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSK1.Click("79;15");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.WebDocument19216801' at 1357;340.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(29));
            repo.WebDocument19216801.WebDocument19216801.MoveTo("1357;340");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1363;436.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(30));
            repo.WebDocument19216801.WebDocument19216801.MoveTo("1363;436");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(31));
            Validate.Attribute(repo.WebDocument19216801.Button7Info, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='submitBtn') on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(32));
            Validate.Attribute(repo.WebDocument19216801.Button7Info, "Class", "submitBtn");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='Apply changes') on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(33));
            Validate.Attribute(repo.WebDocument19216801.Button7Info, "TagValue", "Apply changes");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Apply changes') on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(34));
            Validate.Attribute(repo.WebDocument19216801.Button7Info, "Value", "Apply changes");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot3' with region {X=0,Y=0,Width=166,Height=43}) on item 'WebDocument19216801.Button7'.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(35));
            Validate.ContainsImage(repo.WebDocument19216801.Button7Info, Button7_Screenshot3, Button7_Screenshot3_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Button7' at 72;22.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(36));
            repo.WebDocument19216801.Button7.Click("72;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.WebDocument19216801' at 1355;308.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(37));
            repo.WebDocument19216801.WebDocument19216801.MoveTo("1355;308");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1365;412.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(38));
            repo.WebDocument19216801.WebDocument19216801.MoveTo("1365;412");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'WebDocument19216801.Passphrase' at 63;12.", repo.WebDocument19216801.PassphraseInfo, new RecordItemIndex(39));
            repo.WebDocument19216801.Passphrase.DoubleClick("63;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Passphrase1' at 63;12.", repo.WebDocument19216801.Passphrase1Info, new RecordItemIndex(40));
            repo.WebDocument19216801.Passphrase1.Click("63;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'yahoo' with focus on 'WebDocument19216801.Passphrase1'.", repo.WebDocument19216801.Passphrase1Info, new RecordItemIndex(41));
            repo.WebDocument19216801.Passphrase1.PressKeys("yahoo");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}!{LShiftKey up}23456' with focus on 'WebDocument19216801.Passphrase1'.", repo.WebDocument19216801.Passphrase1Info, new RecordItemIndex(42));
            repo.WebDocument19216801.Passphrase1.PressKeys("{LShiftKey down}!{LShiftKey up}23456");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '6789' with focus on 'WebDocument19216801.Passphrase1'.", repo.WebDocument19216801.Passphrase1Info, new RecordItemIndex(43));
            repo.WebDocument19216801.Passphrase1.PressKeys("6789");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}A{LShiftKey up}' with focus on 'WebDocument19216801.Passphrase1'.", repo.WebDocument19216801.Passphrase1Info, new RecordItemIndex(44));
            repo.WebDocument19216801.Passphrase1.PressKeys("{LShiftKey down}A{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}B{LShiftKey up}' with focus on 'WebDocument19216801.Passphrase1'.", repo.WebDocument19216801.Passphrase1Info, new RecordItemIndex(45));
            repo.WebDocument19216801.Passphrase1.PressKeys("{LShiftKey down}B{LShiftKey up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.PasstextWifi'.", repo.WebDocument19216801.PasstextWifiInfo, new RecordItemIndex(46));
            Validate.Attribute(repo.WebDocument19216801.PasstextWifiInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='pass_text good') on item 'WebDocument19216801.PasstextWifi'.", repo.WebDocument19216801.PasstextWifiInfo, new RecordItemIndex(47));
            Validate.Attribute(repo.WebDocument19216801.PasstextWifiInfo, "Class", "pass_text good");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='passtext_wifi') on item 'WebDocument19216801.PasstextWifi'.", repo.WebDocument19216801.PasstextWifiInfo, new RecordItemIndex(48));
            Validate.Attribute(repo.WebDocument19216801.PasstextWifiInfo, "Id", "passtext_wifi");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Very Strong') on item 'WebDocument19216801.PasstextWifi'.", repo.WebDocument19216801.PasstextWifiInfo, new RecordItemIndex(49));
            Validate.Attribute(repo.WebDocument19216801.PasstextWifiInfo, "InnerText", "Very Strong");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot12' with region {X=0,Y=0,Width=63,Height=14}) on item 'WebDocument19216801.PasstextWifi'.", repo.WebDocument19216801.PasstextWifiInfo, new RecordItemIndex(50));
            Validate.ContainsImage(repo.WebDocument19216801.PasstextWifiInfo, PasstextWifi_Screenshot12, PasstextWifi_Screenshot12_Options);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        CompressedImage SomeSpanTag4_Screenshot1
        { get { return repo.WebDocument19216801.FmSelSecurityModeGrp.SomeSpanTag4Info.GetScreenshot1(new Rectangle(0, 0, 193, 28)); } }

        Imaging.FindOptions SomeSpanTag4_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Disable2_Screenshot1
        { get { return repo.WebDocument19216801.FmSelSecurityModeGrp.Disable2Info.GetScreenshot1(new Rectangle(0, 0, 177, 32)); } }

        Imaging.FindOptions Disable2_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage WPA2PSK_Screenshot1
        { get { return repo.WebDocument19216801.FmSelSecurityModeGrp.WPA2PSKInfo.GetScreenshot1(new Rectangle(0, 0, 177, 32)); } }

        Imaging.FindOptions WPA2PSK_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage WPAPSKWPA2PSK1_Screenshot1
        { get { return repo.WebDocument19216801.FmSelSecurityModeGrp.WPAPSKWPA2PSK1Info.GetScreenshot1(new Rectangle(0, 0, 177, 32)); } }

        Imaging.FindOptions WPAPSKWPA2PSK1_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Passphrase_Screenshot3
        { get { return repo.WebDocument19216801.PassphraseInfo.GetScreenshot3(new Rectangle(0, 0, 213, 20)); } }

        Imaging.FindOptions Passphrase_Screenshot3_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Button7_Screenshot3
        { get { return repo.WebDocument19216801.Button7Info.GetScreenshot3(new Rectangle(0, 0, 166, 43)); } }

        Imaging.FindOptions Button7_Screenshot3_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage PasstextWifi_Screenshot12
        { get { return repo.WebDocument19216801.PasstextWifiInfo.GetScreenshot12(new Rectangle(0, 0, 63, 14)); } }

        Imaging.FindOptions PasstextWifi_Screenshot12_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
