///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Invalid_New_Admin_Change_Password recording.
    /// </summary>
    [TestModule("1f713a6b-17e5-4160-8f5d-b870bea5d5b3", ModuleType.Recording, 1)]
    public partial class Invalid_New_Admin_Change_Password : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Invalid_New_Admin_Change_Password instance = new Invalid_New_Admin_Change_Password();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Invalid_New_Admin_Change_Password()
        {
            currentPassword = "";
            New_Admin_Password = "";
            Reenter_password = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Invalid_New_Admin_Change_Password Instance
        {
            get { return instance; }
        }

#region Variables

        string _currentPassword;

        /// <summary>
        /// Gets or sets the value of variable currentPassword.
        /// </summary>
        [TestVariable("46498eed-99e1-43cc-a571-35c37590acf8")]
        public string currentPassword
        {
            get { return _currentPassword; }
            set { _currentPassword = value; }
        }

        string _New_Admin_Password;

        /// <summary>
        /// Gets or sets the value of variable New_Admin_Password.
        /// </summary>
        [TestVariable("1afbe9f9-8a1c-42bc-bbfd-94998e15430a")]
        public string New_Admin_Password
        {
            get { return _New_Admin_Password; }
            set { _New_Admin_Password = value; }
        }

        string _Reenter_password;

        /// <summary>
        /// Gets or sets the value of variable Reenter_password.
        /// </summary>
        [TestVariable("96988c41-03b4-4cfd-b10f-c419a47a15e6")]
        public string Reenter_password
        {
            get { return _Reenter_password; }
            set { _Reenter_password = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='The password you typed does not meet the requirements.') on item 'WebDocument19216801.ThePasswordYouTypedDoesNotMeetThe'.", repo.WebDocument19216801.ThePasswordYouTypedDoesNotMeetTheInfo, new RecordItemIndex(0));
                //Validate.Attribute(repo.WebDocument19216801.ThePasswordYouTypedDoesNotMeetTheInfo, "InnerText", "The password you typed does not meet the requirements.", Validate.DefaultMessage, false);
                //Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            //Validate.Attribute(repo.WebDocument19216801.CurrentPasswordInfo, "Id", "CurrentPassword");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.CurrentPasswordInfo, "TagName", "input");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.CurrentPasswordInfo, "Tabindex", "2");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.CurrentPasswordInfo, "Type", "text");
            //Delay.Milliseconds(100);
            
            repo.WebDocument19216801.CurrentPassword.Click("82;16");
            Delay.Milliseconds(200);
            
            Keyboard.PrepareFocus(repo.WebDocument19216801.CurrentPassword);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Keyboard.PrepareFocus(repo.WebDocument19216801.CurrentPassword);
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            repo.WebDocument19216801.CurrentPassword.PressKeys(currentPassword);
            Delay.Milliseconds(0);
            
            //Validate.Attribute(repo.WebDocument19216801.NewPasswordInfo, "Id", "NewPassword");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.NewPasswordInfo, "TagName", "input");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.NewPasswordInfo, "Tabindex", "3");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.NewPasswordInfo, "Type", "text");
            //Delay.Milliseconds(100);
            
            //repo.WebDocument19216801.NewPassword.Click("91;12");
            //Delay.Milliseconds(200);
            
            //Keyboard.PrepareFocus(repo.WebDocument19216801.NewPassword);
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Keyboard.PrepareFocus(repo.WebDocument19216801.NewPassword);
            //Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            repo.WebDocumentIE.NewPassword13.Click("81;10");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='NewPassword13') on item 'WebDocumentIE.NewPassword13'.", repo.WebDocumentIE.NewPassword13Info, new RecordItemIndex(17));
            //Validate.Attribute(repo.WebDocumentIE.NewPassword13Info, "Id", "NewPassword13");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='input') on item 'WebDocumentIE.NewPassword13'.", repo.WebDocumentIE.NewPassword13Info, new RecordItemIndex(18));
            //Validate.Attribute(repo.WebDocumentIE.NewPassword13Info, "TagName", "input");
            //Delay.Milliseconds(100);
            
            Keyboard.PrepareFocus(repo.WebDocumentIE.NewPassword13);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Keyboard.PrepareFocus(repo.WebDocumentIE.NewPassword13);
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            repo.WebDocumentIE.NewPassword13.PressKeys(New_Admin_Password);
            Delay.Milliseconds(0);
            
            //Validate.Attribute(repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info, "Class", "skipSVG check-icon");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info, "TagName", "img");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info, "Src", "http://192.168.0.1/skins/lgi/css/images/icon-check.svg");
            //Delay.Milliseconds(100);
            
            //Validate.ContainsImage(repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info, Http19216801SkinsLgiCssImages2_Screenshot1, Http19216801SkinsLgiCssImages2_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://192.168.0.1/skins/lgi/css/images/icon-check.svg') on item 'WebDocument19216801.Http19216801SkinsLgiCssImages2'.", repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info, new RecordItemIndex(26));
            //Validate.Attribute(repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info, "Src", "http://192.168.0.1/skins/lgi/css/images/icon-check.svg");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=24,Height=25}) on item 'WebDocument19216801.Http19216801SkinsLgiCssImages2'.", repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info, new RecordItemIndex(27));
            //Validate.ContainsImage(repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info, Http19216801SkinsLgiCssImages2_Screenshot1_2, Http19216801SkinsLgiCssImages2_Screenshot1_2_Options);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='skipSVG check-icon') on item 'WebDocument19216801.Http19216801SkinsLgiCssImages3'.", repo.WebDocument19216801.Http19216801SkinsLgiCssImages3Info, new RecordItemIndex(28));
            //Validate.Attribute(repo.WebDocument19216801.Http19216801SkinsLgiCssImages3Info, "Class", "skipSVG check-icon");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='skipSVG check-icon') on item 'WebDocument19216801.Http19216801SkinsLgiCssImages3'.", repo.WebDocument19216801.Http19216801SkinsLgiCssImages3Info, new RecordItemIndex(29));
            //Validate.Attribute(repo.WebDocument19216801.Http19216801SkinsLgiCssImages3Info, "Class", "skipSVG check-icon");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Src='http://192.168.0.1/skins/lgi/css/images/icon-check.svg') on item 'WebDocument19216801.Http19216801SkinsLgiCssImages3'.", repo.WebDocument19216801.Http19216801SkinsLgiCssImages3Info, new RecordItemIndex(30));
            //Validate.Attribute(repo.WebDocument19216801.Http19216801SkinsLgiCssImages3Info, "Src", "http://192.168.0.1/skins/lgi/css/images/icon-check.svg");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=22,Height=23}) on item 'WebDocument19216801.Http19216801SkinsLgiCssImages3'.", repo.WebDocument19216801.Http19216801SkinsLgiCssImages3Info, new RecordItemIndex(31));
            //Validate.ContainsImage(repo.WebDocument19216801.Http19216801SkinsLgiCssImages3Info, Http19216801SkinsLgiCssImages3_Screenshot1, Http19216801SkinsLgiCssImages3_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            //Refresh_Screen();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIE.ReenterPassword' at 93;12.", repo.WebDocumentIE.ReenterPasswordInfo, new RecordItemIndex(33));
            repo.WebDocumentIE.ReenterPassword.Click("93;12");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='ReenterPassword') on item 'WebDocumentIE.ReenterPassword'.", repo.WebDocumentIE.ReenterPasswordInfo, new RecordItemIndex(34));
            //Validate.Attribute(repo.WebDocumentIE.ReenterPasswordInfo, "Id", "ReenterPassword");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='input') on item 'WebDocumentIE.ReenterPassword'.", repo.WebDocumentIE.ReenterPasswordInfo, new RecordItemIndex(35));
            //Validate.Attribute(repo.WebDocumentIE.ReenterPasswordInfo, "TagName", "input");
            //Delay.Milliseconds(100);
            
            Keyboard.PrepareFocus(repo.WebDocumentIE.ReenterPassword);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Keyboard.PrepareFocus(repo.WebDocumentIE.ReenterPassword);
            Keyboard.Press(System.Windows.Forms.Keys.Delete, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Reenter_password' with focus on 'WebDocumentIE.ReenterPassword'.", repo.WebDocumentIE.ReenterPasswordInfo, new RecordItemIndex(38));
            repo.WebDocumentIE.ReenterPassword.PressKeys(Reenter_password);
            Delay.Milliseconds(100);
            
            //repo.WebDocument19216801.Button7.Click("102;30");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Button7' at 75;31.", repo.WebDocument19216801.Button7Info, new RecordItemIndex(40));
            repo.WebDocument19216801.Button7.Click("75;31");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='The password you typed does not meet the requirements.') on item 'WebDocument19216801.ThePasswordYouTypedDoesNotMeetThe'.", repo.WebDocument19216801.ThePasswordYouTypedDoesNotMeetTheInfo, new RecordItemIndex(41));
            //Validate.Attribute(repo.WebDocument19216801.ThePasswordYouTypedDoesNotMeetTheInfo, "InnerText", "The password you typed does not meet the requirements.");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='span') on item 'WebDocument19216801.ThePasswordYouTypedDoesNotMeetThe'.", repo.WebDocument19216801.ThePasswordYouTypedDoesNotMeetTheInfo, new RecordItemIndex(42));
            //Validate.Attribute(repo.WebDocument19216801.ThePasswordYouTypedDoesNotMeetTheInfo, "TagName", "span");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=211,Height=43}) on item 'WebDocument19216801.ThePasswordYouTypedDoesNotMeetThe'.", repo.WebDocument19216801.ThePasswordYouTypedDoesNotMeetTheInfo, new RecordItemIndex(43));
            //Validate.ContainsImage(repo.WebDocument19216801.ThePasswordYouTypedDoesNotMeetTheInfo, ThePasswordYouTypedDoesNotMeetThe_Screenshot1, ThePasswordYouTypedDoesNotMeetThe_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='New password does not match. Please try again.') on item 'WebDocumentIE.NewPasswordDoesNotMatchPleaseTry'.", repo.WebDocumentIE.NewPasswordDoesNotMatchPleaseTryInfo, new RecordItemIndex(44));
                //Validate.Attribute(repo.WebDocumentIE.NewPasswordDoesNotMatchPleaseTryInfo, "InnerText", "New password does not match. Please try again.", Validate.DefaultMessage, false);
                //Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(44)); }
            
            try {
                //Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Sorry! There was an error while updating your settings. Please try again a bit later.') on item 'WebDocumentIE.SorryThereWasAnErrorWhileUpdating'.", repo.WebDocumentIE.SorryThereWasAnErrorWhileUpdatingInfo, new RecordItemIndex(45));
                //Validate.Attribute(repo.WebDocumentIE.SorryThereWasAnErrorWhileUpdatingInfo, "InnerText", "Sorry! There was an error while updating your settings. Please try again a bit later.", Validate.DefaultMessage, false);
                //Delay.Milliseconds(100);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(45)); }
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='errTipClose') on item 'WebDocument19216801.ErrCloseNewPassword13'.", repo.WebDocument19216801.ErrCloseNewPassword13Info, new RecordItemIndex(46));
            Validate.Attribute(repo.WebDocument19216801.ErrCloseNewPassword13Info, "Class", "errTipClose");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='errClose-NewPassword13') on item 'WebDocument19216801.ErrCloseNewPassword13'.", repo.WebDocument19216801.ErrCloseNewPassword13Info, new RecordItemIndex(47));
            Validate.Attribute(repo.WebDocument19216801.ErrCloseNewPassword13Info, "Id", "errClose-NewPassword13");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=31,Height=36}) on item 'WebDocument19216801.ErrCloseNewPassword13'.", repo.WebDocument19216801.ErrCloseNewPassword13Info, new RecordItemIndex(48));
            //Validate.ContainsImage(repo.WebDocument19216801.ErrCloseNewPassword13Info, ErrCloseNewPassword13_Screenshot1, ErrCloseNewPassword13_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='errTipClose') on item 'WebDocument19216801.ErrCloseReenterPassword'.", repo.WebDocument19216801.ErrCloseReenterPasswordInfo, new RecordItemIndex(49));
            Validate.Attribute(repo.WebDocument19216801.ErrCloseReenterPasswordInfo, "Class", "errTipClose");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='errClose-ReenterPassword') on item 'WebDocument19216801.ErrCloseReenterPassword'.", repo.WebDocument19216801.ErrCloseReenterPasswordInfo, new RecordItemIndex(50));
            Validate.Attribute(repo.WebDocument19216801.ErrCloseReenterPasswordInfo, "Id", "errClose-ReenterPassword");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=31,Height=36}) on item 'WebDocument19216801.ErrCloseReenterPassword'.", repo.WebDocument19216801.ErrCloseReenterPasswordInfo, new RecordItemIndex(51));
            //Validate.ContainsImage(repo.WebDocument19216801.ErrCloseReenterPasswordInfo, ErrCloseReenterPassword_Screenshot1, ErrCloseReenterPassword_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(52));
            
            Validate_SorryThereWasAnErrorWhileUpdating();
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        CompressedImage Http19216801SkinsLgiCssImages2_Screenshot1
        { get { return repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info.GetScreenshot1(new Rectangle(0, 0, 24, 25)); } }

        Imaging.FindOptions Http19216801SkinsLgiCssImages2_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Http19216801SkinsLgiCssImages2_Screenshot1_2
        { get { return repo.WebDocument19216801.Http19216801SkinsLgiCssImages2Info.GetScreenshot1(new Rectangle(0, 0, 24, 25)); } }

        Imaging.FindOptions Http19216801SkinsLgiCssImages2_Screenshot1_2_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Http19216801SkinsLgiCssImages3_Screenshot1
        { get { return repo.WebDocument19216801.Http19216801SkinsLgiCssImages3Info.GetScreenshot1(new Rectangle(0, 0, 22, 23)); } }

        Imaging.FindOptions Http19216801SkinsLgiCssImages3_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ThePasswordYouTypedDoesNotMeetThe_Screenshot1
        { get { return repo.WebDocument19216801.ThePasswordYouTypedDoesNotMeetTheInfo.GetScreenshot1(new Rectangle(0, 0, 211, 43)); } }

        Imaging.FindOptions ThePasswordYouTypedDoesNotMeetThe_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ErrCloseNewPassword13_Screenshot1
        { get { return repo.WebDocument19216801.ErrCloseNewPassword13Info.GetScreenshot1(new Rectangle(0, 0, 31, 36)); } }

        Imaging.FindOptions ErrCloseNewPassword13_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage ErrCloseReenterPassword_Screenshot1
        { get { return repo.WebDocument19216801.ErrCloseReenterPasswordInfo.GetScreenshot1(new Rectangle(0, 0, 31, 36)); } }

        Imaging.FindOptions ErrCloseReenterPassword_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage SorryThereWasAnErrorWhileUpdating_Screenshot1
        { get { return repo.WebDocumentIE.SorryThereWasAnErrorWhileUpdatingInfo.GetScreenshot1(new Rectangle(0, 0, 0, 0)); } }

        Imaging.FindOptions SorryThereWasAnErrorWhileUpdating_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
