///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Lease_Time_Validation_Recording recording.
    /// </summary>
    [TestModule("5683f326-0708-4e85-832f-022ee4d21e03", ModuleType.Recording, 1)]
    public partial class Lease_Time_Validation_Recording : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Lease_Time_Validation_Recording instance = new Lease_Time_Validation_Recording();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Lease_Time_Validation_Recording()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Lease_Time_Validation_Recording Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='MaxUsers') on item 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(0));
            //Validate.Attribute(repo.WebDocument19216801.MaxUsersInfo, "Id", "MaxUsers");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='155') on item 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(1));
            //Validate.Attribute(repo.WebDocument19216801.MaxUsersInfo, "TagValue", "155");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='155') on item 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(2));
            //Validate.Attribute(repo.WebDocument19216801.MaxUsersInfo, "Value", "155");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.MaxUsers' at 15;14.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(3));
            //repo.WebDocument19216801.MaxUsers.Click("15;14");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(4));
            //Keyboard.PrepareFocus(repo.WebDocument19216801.MaxUsers);
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '277' with focus on 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(5));
            //repo.WebDocument19216801.MaxUsers.PressKeys("277");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(6));
            //repo.WebDocument19216801.MaxUsers.PressKeys("{Tab}");
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='LeaseTime') on item 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.WebDocument19216801.LeaseTimeInfo, "Id", "LeaseTime");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.LeaseTime' at 67;7.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(8));
            repo.WebDocument19216801.LeaseTime.Click("67;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(9));
            Keyboard.PrepareFocus(repo.WebDocument19216801.LeaseTime);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(10));
            repo.WebDocument19216801.LeaseTime.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '100000' with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(11));
            repo.WebDocument19216801.LeaseTime.PressKeys("100000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.DHCPv4' at 60;22.", repo.WebDocument19216801.DHCPv4Info, new RecordItemIndex(12));
            repo.WebDocument19216801.DHCPv4.Click("60;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.LeaseTime' at 69;7.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(13));
            repo.WebDocument19216801.LeaseTime.Click("69;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(14));
            Keyboard.PrepareFocus(repo.WebDocument19216801.LeaseTime);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(15));
            repo.WebDocument19216801.LeaseTime.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abcdedfgh' with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(16));
            repo.WebDocument19216801.LeaseTime.PressKeys("abcdedfgh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.DHCPv4' at 71;17.", repo.WebDocument19216801.DHCPv4Info, new RecordItemIndex(17));
            repo.WebDocument19216801.DHCPv4.Click("71;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='errorTip') on item 'WebDocument19216801.ErrTipLeaseTime'.", repo.WebDocument19216801.ErrTipLeaseTimeInfo, new RecordItemIndex(18));
            Validate.Attribute(repo.WebDocument19216801.ErrTipLeaseTimeInfo, "Class", "errorTip");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='errTip_LeaseTime') on item 'WebDocument19216801.ErrTipLeaseTime'.", repo.WebDocument19216801.ErrTipLeaseTimeInfo, new RecordItemIndex(19));
            Validate.Attribute(repo.WebDocument19216801.ErrTipLeaseTimeInfo, "Id", "errTip_LeaseTime");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=200,Height=49}) on item 'WebDocument19216801.ErrTipLeaseTime'.", repo.WebDocument19216801.ErrTipLeaseTimeInfo, new RecordItemIndex(20));
            Validate.ContainsImage(repo.WebDocument19216801.ErrTipLeaseTimeInfo, ErrTipLeaseTime_Screenshot1, ErrTipLeaseTime_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='errTipClose') on item 'WebDocument19216801.ErrCloseLeaseTime'.", repo.WebDocument19216801.ErrCloseLeaseTimeInfo, new RecordItemIndex(21));
            Validate.Attribute(repo.WebDocument19216801.ErrCloseLeaseTimeInfo, "Class", "errTipClose");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='errClose-LeaseTime') on item 'WebDocument19216801.ErrCloseLeaseTime'.", repo.WebDocument19216801.ErrCloseLeaseTimeInfo, new RecordItemIndex(22));
            Validate.Attribute(repo.WebDocument19216801.ErrCloseLeaseTimeInfo, "Id", "errClose-LeaseTime");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.LeaseTime' at 69;9.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(23));
            repo.WebDocument19216801.LeaseTime.Click("69;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(24));
            Keyboard.PrepareFocus(repo.WebDocument19216801.LeaseTime);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10000000000' with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(25));
            repo.WebDocument19216801.LeaseTime.PressKeys("10000000000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.DHCPv4' at 78;24.", repo.WebDocument19216801.DHCPv4Info, new RecordItemIndex(26));
            repo.WebDocument19216801.DHCPv4.Click("78;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='errTipClose') on item 'WebDocument19216801.ErrCloseLeaseTime'.", repo.WebDocument19216801.ErrCloseLeaseTimeInfo, new RecordItemIndex(27));
            Validate.Attribute(repo.WebDocument19216801.ErrCloseLeaseTimeInfo, "Class", "errTipClose");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='errClose-LeaseTime') on item 'WebDocument19216801.ErrCloseLeaseTime'.", repo.WebDocument19216801.ErrCloseLeaseTimeInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.WebDocument19216801.ErrCloseLeaseTimeInfo, "Id", "errClose-LeaseTime");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='10000000000 must be between 120 and 604800.') on item 'WebDocument19216801.SpanTag10000000000MustBeBetween120A'.", repo.WebDocument19216801.SpanTag10000000000MustBeBetween120AInfo, new RecordItemIndex(29));
            Validate.Attribute(repo.WebDocument19216801.SpanTag10000000000MustBeBetween120AInfo, "InnerText", "10000000000 must be between 120 and 604800.");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.LeaseTime' at 100;11.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(30));
            repo.WebDocument19216801.LeaseTime.Click("100;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}' with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(31));
            repo.WebDocument19216801.LeaseTime.PressKeys("{LControlKey down}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(32));
            Keyboard.PrepareFocus(repo.WebDocument19216801.LeaseTime);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1000000' with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(33));
            repo.WebDocument19216801.LeaseTime.PressKeys("1000000");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.DHCPv4' at 55;22.", repo.WebDocument19216801.DHCPv4Info, new RecordItemIndex(34));
            repo.WebDocument19216801.DHCPv4.Click("55;22");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.LeaseTime' at 68;12.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(35));
            repo.WebDocument19216801.LeaseTime.Click("68;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(36));
            Keyboard.PrepareFocus(repo.WebDocument19216801.LeaseTime);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '84260' with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(37));
            repo.WebDocument19216801.LeaseTime.PressKeys("84260");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.MaxUsers' at 39;4.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(38));
            repo.WebDocument19216801.MaxUsers.Click("39;4");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(39));
            Keyboard.PrepareFocus(repo.WebDocument19216801.MaxUsers);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abc' with focus on 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(40));
            repo.WebDocument19216801.MaxUsers.PressKeys("abc");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.DHCPv4' at 93;23.", repo.WebDocument19216801.DHCPv4Info, new RecordItemIndex(41));
            repo.WebDocument19216801.DHCPv4.Click("93;23");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.LeaseTime' at 76;11.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(42));
            //repo.WebDocument19216801.LeaseTime.Click("76;11");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(43));
            //Keyboard.PrepareFocus(repo.WebDocument19216801.LeaseTime);
            //Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}'.", new RecordItemIndex(44));
            //Keyboard.Press("{Delete}");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='86400') on item 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(45));
            //Validate.Attribute(repo.WebDocument19216801.LeaseTimeInfo, "TagValue", "86400");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Tabindex='7') on item 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(46));
            //Validate.Attribute(repo.WebDocument19216801.LeaseTimeInfo, "Tabindex", "7");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='86400') on item 'WebDocument19216801.LeaseTime'.", repo.WebDocument19216801.LeaseTimeInfo, new RecordItemIndex(47));
            //Validate.Attribute(repo.WebDocument19216801.LeaseTimeInfo, "Value", "86400");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.WebDocument19216801' at 1908;175.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(48));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1908;175");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1918;884.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(49));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1918;884");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.IPDelete' at 90;27.", repo.WebDocument19216801.IPDeleteInfo, new RecordItemIndex(50));
            //repo.WebDocument19216801.IPDelete.Click("90;27");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage ErrTipLeaseTime_Screenshot1
        { get { return repo.WebDocument19216801.ErrTipLeaseTimeInfo.GetScreenshot1(new Rectangle(0, 0, 200, 49)); } }

        Imaging.FindOptions ErrTipLeaseTime_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
