///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_Screen_Router_Status_Upstream_Validation recording.
    /// </summary>
    [TestModule("a87be5fc-4202-4c88-8d21-8c39fbfe4826", ModuleType.Recording, 1)]
    public partial class Login_Screen_Router_Status_Upstream_Validation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Login_Screen_Router_Status_Upstream_Validation instance = new Login_Screen_Router_Status_Upstream_Validation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_Screen_Router_Status_Upstream_Validation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_Screen_Router_Status_Upstream_Validation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Upstream') on item 'WebDocument19216801.RouterStatusTabs.Upstream'.", repo.WebDocument19216801.RouterStatusTabs.UpstreamInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.WebDocument19216801.RouterStatusTabs.UpstreamInfo, "InnerText", "Upstream");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='http://192.168.0.1/#upstream') on item 'WebDocument19216801.RouterStatusTabs.Upstream'.", repo.WebDocument19216801.RouterStatusTabs.UpstreamInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.WebDocument19216801.RouterStatusTabs.UpstreamInfo, "Href", "http://192.168.0.1/#upstream");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.RouterStatusTabs.Upstream' at 49;24.", repo.WebDocument19216801.RouterStatusTabs.UpstreamInfo, new RecordItemIndex(2));
            repo.WebDocument19216801.RouterStatusTabs.Upstream.Click("49;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Upstream bonded channels') on item 'WebDocument19216801.UpstreamBondedChannels'.", repo.WebDocument19216801.UpstreamBondedChannelsInfo, new RecordItemIndex(3));
            Validate.Attribute(repo.WebDocument19216801.UpstreamBondedChannelsInfo, "InnerText", "Upstream bonded channels");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Channel') on item 'WebDocument19216801.Channel'.", repo.WebDocument19216801.ChannelInfo, new RecordItemIndex(4));
            Validate.Attribute(repo.WebDocument19216801.ChannelInfo, "InnerText", "Channel");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Channel ID') on item 'WebDocument19216801.ChannelID'.", repo.WebDocument19216801.ChannelIDInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.WebDocument19216801.ChannelIDInfo, "InnerText", "Channel ID");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Upstream bonded channels') on item 'WebDocument19216801.UpstreamBondedChannels1'.", repo.WebDocument19216801.UpstreamBondedChannels1Info, new RecordItemIndex(6));
            Validate.Attribute(repo.WebDocument19216801.UpstreamBondedChannels1Info, "InnerText", "Upstream bonded channels");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Channel Type') on item 'WebDocument19216801.ChannelType'.", repo.WebDocument19216801.ChannelTypeInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.WebDocument19216801.ChannelTypeInfo, "InnerText", "Channel Type");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.TableContainerLengthdata2' at 636;302.", repo.WebDocument19216801.TableContainerLengthdata2Info, new RecordItemIndex(8));
            repo.WebDocument19216801.TableContainerLengthdata2.MoveTo("636;302");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'WebDocument19216801.TableContainerLengthdata2' at 644;294.", repo.WebDocument19216801.TableContainerLengthdata2Info, new RecordItemIndex(9));
            repo.WebDocument19216801.TableContainerLengthdata2.MoveTo("644;294");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.OverlaycontentHolder2' at 703;720.", repo.WebDocument19216801.OverlaycontentHolder2Info, new RecordItemIndex(10));
            repo.WebDocument19216801.OverlaycontentHolder2.MoveTo("703;720");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(11));
            
            Validate_upstremChannel();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
