///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login_Screen_Router_Status_Network_Log_Validation recording.
    /// </summary>
    [TestModule("852241fa-8f9e-4e17-855d-83825dd0bec2", ModuleType.Recording, 1)]
    public partial class Login_Screen_Router_Status_Network_Log_Validation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Login_Screen_Router_Status_Network_Log_Validation instance = new Login_Screen_Router_Status_Network_Log_Validation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login_Screen_Router_Status_Network_Log_Validation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login_Screen_Router_Status_Network_Log_Validation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            //repo.WebDocument19216801.RouterStatusTabs.NetworkLog.Click("58;23");
            //Delay.Milliseconds(200);
            
            //Validate.Attribute(repo.WebDocument19216801.RouterStatusTabs.NetworkLogInfo, "InnerText", "Network Log");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.RouterStatusTabs.NetworkLogInfo, "Href", "http://192.168.0.1/#networklog");
            //Delay.Milliseconds(100);
            
            //Validate.ContainsImage(repo.WebDocument19216801.RouterStatusTabs.NetworkLogInfo, NetworkLog_Screenshot3, NetworkLog_Screenshot3_Options);
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.RouterStatusTabs.NetworkLog1' at 51;24.", repo.WebDocument19216801.RouterStatusTabs.NetworkLog1Info, new RecordItemIndex(4));
            repo.WebDocument19216801.RouterStatusTabs.NetworkLog1.Click("51;24");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Network Log') on item 'WebDocument19216801.RouterStatusTabs.NetworkLog1'.", repo.WebDocument19216801.RouterStatusTabs.NetworkLog1Info, new RecordItemIndex(5));
            Validate.Attribute(repo.WebDocument19216801.RouterStatusTabs.NetworkLog1Info, "InnerText", "Network Log");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='http://192.168.0.1/#networklog') on item 'WebDocument19216801.RouterStatusTabs.NetworkLog1'.", repo.WebDocument19216801.RouterStatusTabs.NetworkLog1Info, new RecordItemIndex(6));
            Validate.Attribute(repo.WebDocument19216801.RouterStatusTabs.NetworkLog1Info, "Href", "http://192.168.0.1/#networklog");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'WebDocument19216801.RouterStatusTabs.NetworkLog1'.", repo.WebDocument19216801.RouterStatusTabs.NetworkLog1Info, new RecordItemIndex(7));
            Validate.Exists(repo.WebDocument19216801.RouterStatusTabs.NetworkLog1Info);
            Delay.Milliseconds(100);
            
            Report.Screenshot(ReportLevel.Info, "User", "", null, false, new RecordItemIndex(8));
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 30s.", new RecordItemIndex(9));
            //Delay.Duration(30000, false);
            
            View_Network_Logs();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        CompressedImage NetworkLog_Screenshot3
        { get { return repo.WebDocument19216801.RouterStatusTabs.NetworkLogInfo.GetScreenshot3(new Rectangle(0, 0, 135, 58)); } }

        Imaging.FindOptions NetworkLog_Screenshot3_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
