///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NavigateToWirelessGuestNetwork recording.
    /// </summary>
    [TestModule("a5bda70f-f56a-4f69-ae85-f8540a736d3b", ModuleType.Recording, 1)]
    public partial class NavigateToWirelessGuestNetwork : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static NavigateToWirelessGuestNetwork instance = new NavigateToWirelessGuestNetwork();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NavigateToWirelessGuestNetwork()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NavigateToWirelessGuestNetwork Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 25s.", new RecordItemIndex(0));
            Delay.Duration(25000, false);
            
            repo.WebDocument19216801.AdvancedSettings.Click("69;7");
            Delay.Milliseconds(200);
            
            repo.WebDocument19216801.Wireless.Click("23;9");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -120 units.", new RecordItemIndex(3));
            //Mouse.ScrollWheel(-120);
            //Delay.Milliseconds(500);
            
            //Validate.Attribute(repo.WebDocument19216801.GuestNetwork1Info, "Visible", "True");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.GuestNetwork1Info, "InnerText", "Guest network");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Href='http://192.168.0.1/?guest_settings&mid=WirelessGuest') on item 'WebDocument19216801.GuestNetwork1'.", repo.WebDocument19216801.GuestNetwork1Info, new RecordItemIndex(6));
            //Validate.Attribute(repo.WebDocument19216801.GuestNetwork1Info, "Href", "http://192.168.0.1/?guest_settings&mid=WirelessGuest");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=114,Height=13}) on item 'WebDocument19216801.GuestNetwork1'.", repo.WebDocument19216801.GuestNetwork1Info, new RecordItemIndex(7));
            //Validate.ContainsImage(repo.WebDocument19216801.GuestNetwork1Info, GuestNetwork1_Screenshot1, GuestNetwork1_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.GuestNetwork1' at 33;5.", repo.WebDocument19216801.GuestNetwork1Info, new RecordItemIndex(8));
            //repo.WebDocument19216801.GuestNetwork1.Click("33;5");
            //Delay.Milliseconds(200);
            
            repo.WebDocument19216801.GuestNetwork1.Click("24;5");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.LabelWirelessGuest'.", repo.WebDocument19216801.LabelWirelessGuestInfo, new RecordItemIndex(10));
            //Validate.Attribute(repo.WebDocument19216801.LabelWirelessGuestInfo, "Visible", "True");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='label_WirelessGuest') on item 'WebDocument19216801.LabelWirelessGuest'.", repo.WebDocument19216801.LabelWirelessGuestInfo, new RecordItemIndex(11));
            //Validate.Attribute(repo.WebDocument19216801.LabelWirelessGuestInfo, "Id", "label_WirelessGuest");
            //Delay.Milliseconds(100);
            
            //Validate.Attribute(repo.WebDocument19216801.LabelWirelessGuestInfo, "InnerText", "Guest network");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=728,Height=66}) on item 'WebDocument19216801.LabelWirelessGuest'.", repo.WebDocument19216801.LabelWirelessGuestInfo, new RecordItemIndex(13));
            //Validate.ContainsImage(repo.WebDocument19216801.LabelWirelessGuestInfo, LabelWirelessGuest_Screenshot1, LabelWirelessGuest_Screenshot1_Options);
            //Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        CompressedImage GuestNetwork1_Screenshot1
        { get { return repo.WebDocument19216801.GuestNetwork1Info.GetScreenshot1(new Rectangle(0, 0, 114, 13)); } }

        Imaging.FindOptions GuestNetwork1_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage LabelWirelessGuest_Screenshot1
        { get { return repo.WebDocument19216801.LabelWirelessGuestInfo.GetScreenshot1(new Rectangle(0, 0, 728, 66)); } }

        Imaging.FindOptions LabelWirelessGuest_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
