///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Print_Test_Environment_Details recording.
    /// </summary>
    [TestModule("af7c813a-5eb7-455e-8ef8-250f86ee3e5f", ModuleType.Recording, 1)]
    public partial class Print_Test_Environment_Details : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Print_Test_Environment_Details instance = new Print_Test_Environment_Details();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Print_Test_Environment_Details()
        {
            modemEnv = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Print_Test_Environment_Details Instance
        {
            get { return instance; }
        }

#region Variables

        string _modemEnv;

        /// <summary>
        /// Gets or sets the value of variable modemEnv.
        /// </summary>
        [TestVariable("f2948160-b543-4d68-abff-1f2875375183")]
        public string modemEnv
        {
            get { return _modemEnv; }
            set { _modemEnv = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            printTestDetails(modemEnv);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
