///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Refresh_MAC_Filter_Changes recording.
    /// </summary>
    [TestModule("30b0d9ba-266c-4570-a43c-f5f707492f5d", ModuleType.Recording, 1)]
    public partial class Refresh_MAC_Filter_Changes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Refresh_MAC_Filter_Changes instance = new Refresh_MAC_Filter_Changes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Refresh_MAC_Filter_Changes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Refresh_MAC_Filter_Changes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Validate.Attribute(repo.WebDocument19216801.IPAdd1Info, "Id", "IP_Add");
            Delay.Milliseconds(100);
            
            Validate_IPAdd1();
            Delay.Milliseconds(0);
            
            //Validate.Attribute(repo.WebDocument19216801.IPAdd1Info, "TagValue", "Refresh");
            //Delay.Milliseconds(100);
            
            Validate_IPAdd11();
            Delay.Milliseconds(0);
            
            Validate.Attribute(repo.WebDocument19216801.IPAdd1Info, "Value", "Refresh");
            Delay.Milliseconds(100);
            
            repo.WebDocument19216801.IPAdd1.Click("69;35");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage IPAdd1_Screenshot2
        { get { return repo.WebDocument19216801.IPAdd1Info.GetScreenshot2(new Rectangle(0, 0, 0, 0)); } }

        Imaging.FindOptions IPAdd1_Screenshot2_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage IPAdd1_Screenshot2_2
        { get { return repo.WebDocument19216801.IPAdd1Info.GetScreenshot2(new Rectangle(0, 0, 0, 0)); } }

        Imaging.FindOptions IPAdd1_Screenshot2_2_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
