///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Sage_Test1 recording.
    /// </summary>
    [TestModule("3adf58e0-fa15-4b0c-9e6e-5fe4385c73f9", ModuleType.Recording, 1)]
    public partial class Sage_Test1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Sage_Test1 instance = new Sage_Test1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Sage_Test1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Sage_Test1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SageInstruments960CProgramFiles.File' at 16;8.", repo.SageInstruments960CProgramFiles.FileInfo, new RecordItemIndex(0));
            repo.SageInstruments960CProgramFiles.File.Click("16;8");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Sage960.LoadCfgFile' at 112;9.", repo.Sage960.LoadCfgFileInfo, new RecordItemIndex(1));
            //repo.Sage960.LoadCfgFile.Click("112;9");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.DS0TestsCfg' at 78;14.", repo.Open.DS0TestsCfgInfo, new RecordItemIndex(2));
            //repo.Open.DS0TestsCfg.Click("78;14");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Open.ButtonOpen' at 36;12.", repo.Open.ButtonOpenInfo, new RecordItemIndex(3));
            //repo.Open.ButtonOpen.Click("36;12");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SageInstruments960CProgramFiles.View' at 22;7.", repo.SageInstruments960CProgramFiles.ViewInfo, new RecordItemIndex(4));
            repo.SageInstruments960CProgramFiles.View.Click("22;7");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Sage960.Exit' at 54;6.", repo.Sage960.ExitInfo, new RecordItemIndex(5));
            //repo.Sage960.Exit.Click("54;6");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SageInstruments960CProgramFiles.Cell2W600' at 44;17.", repo.SageInstruments960CProgramFiles.Cell2W600Info, new RecordItemIndex(6));
            repo.SageInstruments960CProgramFiles.Cell2W600.Click("44;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SageInstruments960CProgramFiles.ConfigureSpan' at 80;18.", repo.SageInstruments960CProgramFiles.ConfigureSpanInfo, new RecordItemIndex(7));
            repo.SageInstruments960CProgramFiles.ConfigureSpan.Click("80;18");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SageInstruments960CProgramFiles.ButtonEqBack' at 46;8.", repo.SageInstruments960CProgramFiles.ButtonEqBackInfo, new RecordItemIndex(8));
            repo.SageInstruments960CProgramFiles.ButtonEqBack.Click("46;8");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Run') on item 'SageInstruments960CProgramFiles.ButtonRun'.", repo.SageInstruments960CProgramFiles.ButtonRunInfo, new RecordItemIndex(9));
            //Validate.Attribute(repo.SageInstruments960CProgramFiles.ButtonRunInfo, "Text", "Run");
            //Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SageInstruments960CProgramFiles.ButtonRun' at 33;9.", repo.SageInstruments960CProgramFiles.ButtonRunInfo, new RecordItemIndex(10));
            //repo.SageInstruments960CProgramFiles.ButtonRun.MoveTo("33;9");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'SageInstruments960CProgramFiles.ButtonRun' at 33;9.", repo.SageInstruments960CProgramFiles.ButtonRunInfo, new RecordItemIndex(11));
            //repo.SageInstruments960CProgramFiles.ButtonRun.MoveTo("33;9");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SageInstruments960CProgramFiles.Stop' at 45;13.", repo.SageInstruments960CProgramFiles.StopInfo, new RecordItemIndex(12));
            //repo.SageInstruments960CProgramFiles.Stop.Click("45;13");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'SageInstruments960CProgramFiles.Cell2W600' at 67;11.", repo.SageInstruments960CProgramFiles.Cell2W600Info, new RecordItemIndex(13));
            repo.SageInstruments960CProgramFiles.Cell2W600.DoubleClick("67;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'CaptureWindow' at 135;240.", repo.CaptureWindow.SelfInfo, new RecordItemIndex(14));
            repo.CaptureWindow.Self.DoubleClick("135;240");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SageInstruments960CProgramFiles.ButtonRun' at 40;16.", repo.SageInstruments960CProgramFiles.ButtonRunInfo, new RecordItemIndex(15));
            //repo.SageInstruments960CProgramFiles.ButtonRun.Click("40;16");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 1m.", new RecordItemIndex(16));
            //Delay.Duration(60000, false);
            
            //DoDelay();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SageInstruments960CProgramFiles.ButtonEqBack' at 51;10.", repo.SageInstruments960CProgramFiles.ButtonEqBackInfo, new RecordItemIndex(18));
            //repo.SageInstruments960CProgramFiles.ButtonEqBack.Click("51;10");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SageInstruments960CProgramFiles.ButtonEqBack' at 51;10.", repo.SageInstruments960CProgramFiles.ButtonEqBackInfo, new RecordItemIndex(19));
            //repo.SageInstruments960CProgramFiles.ButtonEqBack.Click("51;10");
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
