///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Traceroute1 recording.
    /// </summary>
    [TestModule("ecb6901f-f1b3-491f-864d-bf9d97e4f9cf", ModuleType.Recording, 1)]
    public partial class Traceroute1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Traceroute1 instance = new Traceroute1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Traceroute1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Traceroute1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.AdvancedSettings'.", repo.WebDocument19216801.AdvancedSettingsInfo, new RecordItemIndex(0));
            Validate.Attribute(repo.WebDocument19216801.AdvancedSettingsInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Advanced settings') on item 'WebDocument19216801.AdvancedSettings'.", repo.WebDocument19216801.AdvancedSettingsInfo, new RecordItemIndex(1));
            Validate.Attribute(repo.WebDocument19216801.AdvancedSettingsInfo, "InnerText", "Advanced settings");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=125,Height=19}) on item 'WebDocument19216801.AdvancedSettings'.", repo.WebDocument19216801.AdvancedSettingsInfo, new RecordItemIndex(2));
            Validate.ContainsImage(repo.WebDocument19216801.AdvancedSettingsInfo, AdvancedSettings_Screenshot2, AdvancedSettings_Screenshot2_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.AdvancedSettings' at 61;9.", repo.WebDocument19216801.AdvancedSettingsInfo, new RecordItemIndex(3));
            repo.WebDocument19216801.AdvancedSettings.Click("61;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -360 units.", new RecordItemIndex(4));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.Tools'.", repo.WebDocument19216801.ToolsInfo, new RecordItemIndex(5));
            Validate.Attribute(repo.WebDocument19216801.ToolsInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Tools') on item 'WebDocument19216801.Tools'.", repo.WebDocument19216801.ToolsInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.WebDocument19216801.ToolsInfo, "InnerText", "Tools");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Tools' at 8;8.", repo.WebDocument19216801.ToolsInfo, new RecordItemIndex(7));
            repo.WebDocument19216801.Tools.Click("8;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -240 units.", new RecordItemIndex(8));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(500);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='False') on item 'WebDocument19216801.Traceroute'.", repo.WebDocument19216801.TracerouteInfo, new RecordItemIndex(9));
            //Validate.Attribute(repo.WebDocument19216801.TracerouteInfo, "Visible", "False");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Traceroute') on item 'WebDocument19216801.Traceroute'.", repo.WebDocument19216801.TracerouteInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.WebDocument19216801.TracerouteInfo, "InnerText", "Traceroute");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Traceroute' at 30;7.", repo.WebDocument19216801.TracerouteInfo, new RecordItemIndex(11));
            repo.WebDocument19216801.Traceroute.Click("30;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.LabelTraceRoute'.", repo.WebDocument19216801.LabelTraceRouteInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.WebDocument19216801.LabelTraceRouteInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='label_TraceRoute') on item 'WebDocument19216801.LabelTraceRoute'.", repo.WebDocument19216801.LabelTraceRouteInfo, new RecordItemIndex(13));
            Validate.Attribute(repo.WebDocument19216801.LabelTraceRouteInfo, "Id", "label_TraceRoute");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Traceroute') on item 'WebDocument19216801.LabelTraceRoute'.", repo.WebDocument19216801.LabelTraceRouteInfo, new RecordItemIndex(14));
            Validate.Attribute(repo.WebDocument19216801.LabelTraceRouteInfo, "InnerText", "Traceroute");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=728,Height=66}) on item 'WebDocument19216801.LabelTraceRoute'.", repo.WebDocument19216801.LabelTraceRouteInfo, new RecordItemIndex(15));
            Validate.ContainsImage(repo.WebDocument19216801.LabelTraceRouteInfo, LabelTraceRoute_Screenshot1, LabelTraceRoute_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.WebDocument19216801' at 1360;248.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(16));
            repo.WebDocument19216801.WebDocument19216801.MoveTo("1360;248");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1346;363.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(17));
            repo.WebDocument19216801.WebDocument19216801.MoveTo("1346;363");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.Target'.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(18));
            Validate.Attribute(repo.WebDocument19216801.TargetInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='Target') on item 'WebDocument19216801.Target'.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(19));
            Validate.Attribute(repo.WebDocument19216801.TargetInfo, "Id", "Target");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='') on item 'WebDocument19216801.Target'.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(20));
            //Validate.Attribute(repo.WebDocument19216801.TargetInfo, "InnerText", "");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Target' at 25;7.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(21));
            repo.WebDocument19216801.Target.Click("25;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'www.google.com' with focus on 'WebDocument19216801.Target'.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(22));
            repo.WebDocument19216801.Target.PressKeys("www.google.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(23));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='submitBtn') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(24));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "Class", "submitBtn");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='Start') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(25));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "Id", "Start");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='Start test') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(26));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "TagValue", "Start test");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Start test') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(27));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "Value", "Start test");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=122,Height=42}) on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(28));
            Validate.ContainsImage(repo.WebDocument19216801.StartInfo, Start_Screenshot1, Start_Screenshot1_Options);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Start' at 61;15.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(29));
            repo.WebDocument19216801.Start.Click("61;15");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='submitBtn disabled') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(30));
            //Validate.Attribute(repo.WebDocument19216801.StartInfo, "Class", "submitBtn disabled");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='Start') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(31));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "Id", "Start");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='input') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(32));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "TagName", "input");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='Start test') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(33));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "TagValue", "Start test");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Disabled='disabled') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(34));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "Disabled", "disabled");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='Start test') on item 'WebDocument19216801.Start'.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(35));
            Validate.Attribute(repo.WebDocument19216801.StartInfo, "Value", "Start test");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.WebDocument19216801' at 1359;252.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(36));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1359;252");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1350;310.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(37));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1350;310");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.TraceResult' at 685;54.", repo.WebDocument19216801.TraceResultInfo, new RecordItemIndex(38));
            repo.WebDocument19216801.TraceResult.MoveTo("685;54");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.TraceResult' at 688;44.", repo.WebDocument19216801.TraceResultInfo, new RecordItemIndex(39));
            repo.WebDocument19216801.TraceResult.MoveTo("688;44");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.WebDocument19216801' at 1356;387.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(40));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1356;387");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1335;215.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(41));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1335;215");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
        }

#region Image Feature Data
        CompressedImage AdvancedSettings_Screenshot2
        { get { return repo.WebDocument19216801.AdvancedSettingsInfo.GetScreenshot2(new Rectangle(0, 0, 125, 19)); } }

        Imaging.FindOptions AdvancedSettings_Screenshot2_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage LabelTraceRoute_Screenshot1
        { get { return repo.WebDocument19216801.LabelTraceRouteInfo.GetScreenshot1(new Rectangle(0, 0, 728, 66)); } }

        Imaging.FindOptions LabelTraceRoute_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

        CompressedImage Start_Screenshot1
        { get { return repo.WebDocument19216801.StartInfo.GetScreenshot1(new Rectangle(0, 0, 122, 42)); } }

        Imaging.FindOptions Start_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
