///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The TRouteRecording7 recording.
    /// </summary>
    [TestModule("e9341764-1bef-47df-81db-9f2b3232e338", ModuleType.Recording, 1)]
    public partial class TRouteRecording7 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static TRouteRecording7 instance = new TRouteRecording7();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public TRouteRecording7()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static TRouteRecording7 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://192.168.0.1' with browser 'IE' in normal mode.", new RecordItemIndex(0));
            Host.Local.OpenBrowser("http://192.168.0.1", "IE", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.Password' at 146;11.", repo.WebDocument19216801.PasswordInfo, new RecordItemIndex(1));
            repo.WebDocument19216801.Password.MoveTo("146;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.Password' at 39;11.", repo.WebDocument19216801.PasswordInfo, new RecordItemIndex(2));
            repo.WebDocument19216801.Password.MoveTo("39;11");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}V{LShiftKey up}irgin123' with focus on 'WebDocument19216801.Password'.", repo.WebDocument19216801.PasswordInfo, new RecordItemIndex(3));
            repo.WebDocument19216801.Password.PressKeys("{LShiftKey down}V{LShiftKey up}irgin123");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Button' at 60;17.", repo.WebDocument19216801.ButtonInfo, new RecordItemIndex(4));
            repo.WebDocument19216801.Button.Click("60;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.AdvancedSettings' at 61;9.", repo.WebDocument19216801.AdvancedSettingsInfo, new RecordItemIndex(5));
            repo.WebDocument19216801.AdvancedSettings.Click("61;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -360 units.", new RecordItemIndex(6));
            Mouse.ScrollWheel(-360);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Tools' at 24;11.", repo.WebDocument19216801.ToolsInfo, new RecordItemIndex(7));
            repo.WebDocument19216801.Tools.Click("24;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Scroll Vertical by -120 units.", new RecordItemIndex(8));
            Mouse.ScrollWheel(-120);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Traceroute' at 34;9.", repo.WebDocument19216801.TracerouteInfo, new RecordItemIndex(9));
            repo.WebDocument19216801.Traceroute.Click("34;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Visible='True') on item 'WebDocument19216801.Target'.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(10));
            Validate.Attribute(repo.WebDocument19216801.TargetInfo, "Visible", "True");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='fmZero') on item 'WebDocument19216801.Target'.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(11));
            Validate.Attribute(repo.WebDocument19216801.TargetInfo, "Class", "fmZero");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='Target') on item 'WebDocument19216801.Target'.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(12));
            Validate.Attribute(repo.WebDocument19216801.TargetInfo, "Id", "Target");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Target' at 23;17.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(13));
            repo.WebDocument19216801.Target.Click("23;17");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'www' with focus on 'WebDocument19216801.Target'.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(14));
            repo.WebDocument19216801.Target.PressKeys("www");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.google.com' with focus on 'WebDocument19216801.Target'.", repo.WebDocument19216801.TargetInfo, new RecordItemIndex(15));
            repo.WebDocument19216801.Target.PressKeys(".google.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.Maxhops' at 18;11.", repo.WebDocument19216801.MaxhopsInfo, new RecordItemIndex(16));
            repo.WebDocument19216801.Maxhops.MoveTo("18;11");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'WebDocument19216801.Maxhops' at 26;3.", repo.WebDocument19216801.MaxhopsInfo, new RecordItemIndex(17));
            repo.WebDocument19216801.Maxhops.MoveTo("26;3");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.MaxHops1' at 87;15.", repo.WebDocument19216801.MaxHops1Info, new RecordItemIndex(18));
            repo.WebDocument19216801.MaxHops1.MoveTo("87;15");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '1' with focus on 'WebDocument19216801.Maxhops'.", repo.WebDocument19216801.MaxhopsInfo, new RecordItemIndex(19));
            repo.WebDocument19216801.Maxhops.PressKeys("1");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'WebDocument19216801.Maxhops'.", repo.WebDocument19216801.MaxhopsInfo, new RecordItemIndex(20));
            repo.WebDocument19216801.Maxhops.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.Baseport' at 49;3.", repo.WebDocument19216801.BaseportInfo, new RecordItemIndex(21));
            repo.WebDocument19216801.Baseport.MoveTo("49;3");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'WebDocument19216801.Baseport' at 57;-5.", repo.WebDocument19216801.BaseportInfo, new RecordItemIndex(22));
            repo.WebDocument19216801.Baseport.MoveTo("57;-5");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.SomeSpanTag2' at 2;8.", repo.WebDocument19216801.SomeSpanTag2Info, new RecordItemIndex(23));
            repo.WebDocument19216801.SomeSpanTag2.MoveTo("2;8");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '33434' with focus on 'WebDocument19216801.Baseport'.", repo.WebDocument19216801.BaseportInfo, new RecordItemIndex(24));
            repo.WebDocument19216801.Baseport.PressKeys("33434");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Maxhops' at 29;7.", repo.WebDocument19216801.MaxhopsInfo, new RecordItemIndex(25));
            repo.WebDocument19216801.Maxhops.Click("29;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='Maxhops') on item 'WebDocument19216801.Maxhops'.", repo.WebDocument19216801.MaxhopsInfo, new RecordItemIndex(26));
            Validate.Attribute(repo.WebDocument19216801.MaxhopsInfo, "Id", "Maxhops");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagName='input') on item 'WebDocument19216801.Maxhops'.", repo.WebDocument19216801.MaxhopsInfo, new RecordItemIndex(27));
            Validate.Attribute(repo.WebDocument19216801.MaxhopsInfo, "TagName", "input");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='10') on item 'WebDocument19216801.Maxhops'.", repo.WebDocument19216801.MaxhopsInfo, new RecordItemIndex(28));
            Validate.Attribute(repo.WebDocument19216801.MaxhopsInfo, "TagValue", "10");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='10') on item 'WebDocument19216801.Maxhops'.", repo.WebDocument19216801.MaxhopsInfo, new RecordItemIndex(29));
            Validate.Attribute(repo.WebDocument19216801.MaxhopsInfo, "Value", "10");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='fmZero') on item 'WebDocument19216801.Baseport'.", repo.WebDocument19216801.BaseportInfo, new RecordItemIndex(30));
            Validate.Attribute(repo.WebDocument19216801.BaseportInfo, "Class", "fmZero");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='Baseport') on item 'WebDocument19216801.Baseport'.", repo.WebDocument19216801.BaseportInfo, new RecordItemIndex(31));
            Validate.Attribute(repo.WebDocument19216801.BaseportInfo, "Id", "Baseport");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='') on item 'WebDocument19216801.Baseport'.", repo.WebDocument19216801.BaseportInfo, new RecordItemIndex(32));
            //Validate.Attribute(repo.WebDocument19216801.BaseportInfo, "InnerText", "");
            //Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (TagValue='33434') on item 'WebDocument19216801.Baseport'.", repo.WebDocument19216801.BaseportInfo, new RecordItemIndex(33));
            Validate.Attribute(repo.WebDocument19216801.BaseportInfo, "TagValue", "33434");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Value='33434') on item 'WebDocument19216801.Baseport'.", repo.WebDocument19216801.BaseportInfo, new RecordItemIndex(34));
            Validate.Attribute(repo.WebDocument19216801.BaseportInfo, "Value", "33434");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.Start' at 57;17.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(35));
            repo.WebDocument19216801.Start.Click("57;17");
            Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.Start' at 1360;436.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(36));
            //repo.WebDocument19216801.Start.MoveTo("1360;436");
            //Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'WebDocument19216801.Start' at 1368;428.", repo.WebDocument19216801.StartInfo, new RecordItemIndex(37));
            //repo.WebDocument19216801.Start.MoveTo("1368;428");
            //Delay.Milliseconds(200);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1356;454.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(38));
            //repo.WebDocument19216801.WebDocument19216801.MoveTo("1356;454");
            //Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.TraceResult' at 690;64.", repo.WebDocument19216801.TraceResultInfo, new RecordItemIndex(39));
            repo.WebDocument19216801.TraceResult.MoveTo("690;64");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.TraceResult' at 692;141.", repo.WebDocument19216801.TraceResultInfo, new RecordItemIndex(40));
            repo.WebDocument19216801.TraceResult.MoveTo("692;141");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'WebDocument19216801.WebDocument19216801' at 1359;440.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(41));
            repo.WebDocument19216801.WebDocument19216801.MoveTo("1359;440");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'WebDocument19216801.WebDocument19216801' at 1353;296.", repo.WebDocument19216801.WebDocument19216801Info, new RecordItemIndex(42));
            repo.WebDocument19216801.WebDocument19216801.MoveTo("1353;296");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.LogOut' at 25;6.", repo.WebDocument19216801.LogOutInfo, new RecordItemIndex(43));
            repo.WebDocument19216801.LogOut.Click("25;6");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
