///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Valid_No_of_CPEs_Field_Validation recording.
    /// </summary>
    [TestModule("26e96484-41d8-41d2-9f12-b5e17b077430", ModuleType.Recording, 1)]
    public partial class Valid_No_of_CPEs_Field_Validation : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Valid_No_of_CPEs_Field_Validation instance = new Valid_No_of_CPEs_Field_Validation();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Valid_No_of_CPEs_Field_Validation()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Valid_No_of_CPEs_Field_Validation Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.MaxUsers' at 49;14.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(0));
            repo.WebDocument19216801.MaxUsers.Click("49;14");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.WebDocument19216801.MaxUsers);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete}' with focus on 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(2));
            repo.WebDocument19216801.MaxUsers.PressKeys("{Delete}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'abb' with focus on 'WebDocument19216801.MaxUsers'.", repo.WebDocument19216801.MaxUsersInfo, new RecordItemIndex(3));
            repo.WebDocument19216801.MaxUsers.PressKeys("abb");
            Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.DHCPv4' at 58;24.", repo.WebDocument19216801.DHCPv4Info, new RecordItemIndex(4));
            //repo.WebDocument19216801.DHCPv4.Click("58;24");
            //Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocument19216801.DHCPv4' at 73;20.", repo.WebDocument19216801.DHCPv4Info, new RecordItemIndex(5));
            repo.WebDocument19216801.DHCPv4.Click("73;20");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Id='confirm-wizard') on item 'WebDocumentIE.ConfirmWizard1.ConfirmWizard'.", repo.WebDocumentIE.ConfirmWizard1.ConfirmWizardInfo, new RecordItemIndex(6));
            Validate.Attribute(repo.WebDocumentIE.ConfirmWizard1.ConfirmWizardInfo, "Id", "confirm-wizard");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Class='confirm-wizard-text') on item 'WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdated'.", repo.WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdatedInfo, new RecordItemIndex(7));
            Validate.Attribute(repo.WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdatedInfo, "Class", "confirm-wizard-text");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Your settings have been updated.') on item 'WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdated'.", repo.WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdatedInfo, new RecordItemIndex(8));
            Validate.Attribute(repo.WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdatedInfo, "InnerText", "Your settings have been updated.");
            Delay.Milliseconds(100);
            
            //Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot2' with region {X=0,Y=0,Width=237,Height=48}) on item 'WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdated'.", repo.WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdatedInfo, new RecordItemIndex(9));
            //Validate.ContainsImage(repo.WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdatedInfo, YourSettingsHaveBeenUpdated_Screenshot2, YourSettingsHaveBeenUpdated_Screenshot2_Options);
            //Delay.Milliseconds(100);
            
        }

#region Image Feature Data
        CompressedImage YourSettingsHaveBeenUpdated_Screenshot2
        { get { return repo.WebDocumentIE.ConfirmWizard1.YourSettingsHaveBeenUpdatedInfo.GetScreenshot2(new Rectangle(0, 0, 237, 48)); } }

        Imaging.FindOptions YourSettingsHaveBeenUpdated_Screenshot2_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
