///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validate_Valid_Gateway_LAN_IP recording.
    /// </summary>
    [TestModule("bf0a6d0f-ad2a-47eb-a52a-70f83b0b8062", ModuleType.Recording, 1)]
    public partial class Validate_Valid_Gateway_LAN_IP : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static Validate_Valid_Gateway_LAN_IP instance = new Validate_Valid_Gateway_LAN_IP();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validate_Valid_Gateway_LAN_IP()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validate_Valid_Gateway_LAN_IP Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIE.StartIPAddress2' at 26;12.", repo.WebDocumentIE.StartIPAddress2Info, new RecordItemIndex(0));
            repo.WebDocumentIE.StartIPAddress2.Click("26;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocumentIE.StartIPAddress2'.", repo.WebDocumentIE.StartIPAddress2Info, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.WebDocumentIE.StartIPAddress2);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Delete down}{Back}{Delete up}' with focus on 'WebDocumentIE.StartIPAddress2'.", repo.WebDocumentIE.StartIPAddress2Info, new RecordItemIndex(2));
            repo.WebDocumentIE.StartIPAddress2.PressKeys("{Delete down}{Back}{Delete up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '0' with focus on 'WebDocumentIE.StartIPAddress2'.", repo.WebDocumentIE.StartIPAddress2Info, new RecordItemIndex(3));
            repo.WebDocumentIE.StartIPAddress2.PressKeys("0");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIE.StartIPAddress3' at 16;12.", repo.WebDocumentIE.StartIPAddress3Info, new RecordItemIndex(4));
            repo.WebDocumentIE.StartIPAddress3.Click("16;12");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'WebDocumentIE.StartIPAddress3'.", repo.WebDocumentIE.StartIPAddress3Info, new RecordItemIndex(5));
            Keyboard.PrepareFocus(repo.WebDocumentIE.StartIPAddress3);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '10' with focus on 'WebDocumentIE.StartIPAddress3'.", repo.WebDocumentIE.StartIPAddress3Info, new RecordItemIndex(6));
            repo.WebDocumentIE.StartIPAddress3.PressKeys("10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'WebDocumentIE.DHCPv4' at 69;25.", repo.WebDocumentIE.DHCPv4Info, new RecordItemIndex(7));
            repo.WebDocumentIE.DHCPv4.Click("69;25");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
