///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace ArrisTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The WiFi_5GHz_Broadcast_Enable recording.
    /// </summary>
    [TestModule("2962ffe8-4af6-4f86-ae97-efb9078a3c61", ModuleType.Recording, 1)]
    public partial class WiFi_5GHz_Broadcast_Enable : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MercuryTest1Repository repository.
        /// </summary>
        public static MercuryTest1Repository repo = MercuryTest1Repository.Instance;

        static WiFi_5GHz_Broadcast_Enable instance = new WiFi_5GHz_Broadcast_Enable();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public WiFi_5GHz_Broadcast_Enable()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static WiFi_5GHz_Broadcast_Enable Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Validate.Attribute(repo.WebDocumentIE.FmRbtnEnableSSIDBroadcastSecurity50Info, "Id", "fmRbtn-EnableSSIDBroadcastSecurity50");
            Delay.Milliseconds(100);
            
            repo.WebDocumentIE.FmRbtnEnableSSIDBroadcastSecurity50.Click("14;18");
            Delay.Milliseconds(200);
            
            Capture_5GHz_Broadcast_Enable();
            Delay.Milliseconds(0);
            
            repo.WebDocument19216801.Button25.Click("102;31");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
